### PR TITLE
Update services.cfg

### PR DESCRIPTION
**Pull request by kgoderis**
Inclusion of opml URL definition as not done/omitted in ESH

Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks. Actually, we should remove it from services.cfg and add it right in here: https://github.com/kaikreuzer/openhab-core/blob/master/features/openhab-esh-addons/src/main/feature/feature.xml#L27, that would be even better.

**Comment by maggu2810** [comment]
Why not here https://github.com/eclipse/smarthome/blob/4ab38d71/features/karaf/src/main/feature/feature.xml#L125

**Comment by maggu2810** [comment]
Is this openHAB specific. What is the URL used for?

**Comment by kaikreuzer** [comment]
Because we were not allowed to refer to this url within ESH. That's the whole point why we designed it as a configuration property.

**Pull request merged**
