### PR TITLE
Update Z-Smart Systems ZigBee libraries to 1.3.2

### PR DESCRIPTION
**Pull request by cdjackson**
To be merged with https://github.com/openhab/org.openhab.binding.zigbee/pull/563
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Unless it contains any fix for critical bugs, I'd merge this after the 2.5.3 release.

**Comment by cdjackson** [comment]
Yes, it contains a critical bug fix as we discussed prior to the last update.

**Comment by kaikreuzer** [comment]
Ok, so I will merge right away and start a new snapshot build. Could you verify that everything is working as expected by tonight?

**Comment by cdjackson** [comment]
The main bug fix is with the CC2531 which I can’t personally verify, but others have been using updated libraries for the past month and I understand it fixes the issue (and works ;) ).

I will check that in general it is working though - thanks.

**Pull request merged**
