### PR TITLE
create tmp folder if it does not exist

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@BClark09 & @ThomDietrich This should make the upgrade process (slightly) easier as we do not have to make sure that there the tmp folder within userdata already exists - the upgrade can simply delete it, just like it deletes the cache folder.

**Comment by BClark09** [comment]
Nice, that makes the script I mentioned earlier a little more valid!

**Comment by Celaeno1** [comment]
There is an "error" in **oh2_dir_layout.bat**, line **26**. It begins with **#** , but it should be a REM or **::**

**Comment by BClark09** [comment]
Eek! Good spot, did you want to make a pull request changing it to REM?

**Comment by Celaeno1** [comment]
Unfortunately not, please do it.

**Comment by kaikreuzer** [comment]
Oops, I indeed added the comment AFTER testing it... Thanks for noticing!

**Comment by kaikreuzer** [comment]
I hope this looks better: https://github.com/openhab/openhab-distro/commit/d395831f81a6a023f05a8e8b1cb3742910e66b4b

**Comment by Celaeno1** [comment]
@kaikreuzer Thanks for correcting it!

**Pull request merged**
