### PR TITLE
Update to Karaf 4.1.4

### PR DESCRIPTION
**Pull request by splatch**
This commit just lift up karaf version and removes overrides which are integrated into Karaf codebase.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Did you check whether Karaf 4.1.4 brings any other changes in cfg or start files that would need to be sync'ed here as well?
Also note that the Karaf version update needs to be done in sync with https://github.com/openhab/openhab-core/blob/master/poms/pom.xml#L63.

Did you already do extensive testing to see whether there are any regressions?

Btw, as we are again have some time until a next release, I rather planned to directly move to Karaf 4.2. Do you see any reason against that?

**Comment by splatch** [comment]
Coming back to this after a while. There are no major changes in Karaf 4.1.4 beside bugfixes, most important ones are confirmed to be solved. I haven't done any major testing of this.

On Karaf 4.2 will definitely bring some new semantics. There is major rework of features internals which will support feature level overrides. This will likely cause hiccups during update. Safest option would be to stay on 4.1.x untill 4.2 line gets first patch release.

**Comment by kaikreuzer** [comment]
Ok, we could update to 4.1.4 to resolve some smaller issues, but what you write rather reassures me that we should asap do testing of 4.2.0.M2, so that any major regressions could actually be addressed in an 4.2.0 release. Waiting for a 4.2.1 just hoping that it'll be all fine and stable is probably pretty risky, don't you think?

**Comment by kaikreuzer** [comment]
FTR, the reason why I would like to move to 4.2 soon is https://github.com/openhab/openhab-distro/issues/516, which is imho a pretty important feature for the future update process.

**Comment by splatch** [comment]
Following upstream is best way to integrate early. If you are ok with some bumpy builds, that's the way to go.

Karaf 4.1.4 is already on Log4j2 via pax-logging 1.10.1 - meaning it shares same version of logging backend as 4.2 line and #516 can be tested even now - with 4.1.3 used in assembly.

**Comment by kaikreuzer** [comment]
>  If you are ok with some bumpy builds, that's the way to go.

Better now than close to a release...

Note that #516 requires [KARAF-5354](https://issues.apache.org/jira/browse/KARAF-5354), which isn't part of Karaf 4.1.4, if I am not mistaken.

**Comment by DanielMalmgren** [comment]
Just so that it's mentioned here as well: Quite many of us would be happy to get [this](https://issues.apache.org/jira/browse/KARAF-5473) fix in, which should happen in 4.1.5 and 4.2.0.

**Comment by kaikreuzer** [comment]
Superseded by https://github.com/openhab/openhab-distro/pull/655.

**Pull request closed without merging**
