### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by bobadair**
Update version to 2.5.7-SNAPSHOT in pom.xml.

### CODE REVIEW

**Comment by Hilbrand** [comment]
needs more changes, see #1091

**Comment by cweitkamp** [comment]
Thank you for submitting the changes. We additionally have  #1116 but I am not sure if @ssalonen is still working on it.

**Comment by ssalonen** [comment]
> Thank you for submitting the changes. We additionally have  #1116 but I am not sure if @ssalonen is still working on it.

Thanks for the ping. I think #1116 is already obsolete, and should be recreated with up-to-date dependencies. I will close it up

**Comment by bobadair** [comment]
Ok. Also updated app.bndrun as per #1091 .

**Pull request merged**
