### PR TITLE
Update repo updatepolicy settings

### PR DESCRIPTION
**Pull request by dvanherbergen**
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
Has this PR broken the feature verification?

**Comment by maggu2810** [comment]
See Jenkins report details of #103

**Comment by dvanherbergen** [comment]
No. That PR was already included in the build https://openhab.ci.cloudbees.com/job/openHAB-Distribution/96/ which was successful.
I also tried to build locally and that works too. There must be a different cause.

**Comment by dvanherbergen** [comment]
@maggu2810, the regular build keeps working as normal. It contains entries like:
```
mvn:de.maggu2810.p2redist/com.google.inject/3.0.0.v201312141243
```
The PR build doesn't want to work and it contains entries like:
```
mvn:de.maggu2810.playground.shk.p2fetch/com.google.inject-3.0.0.v201312141243/1.0.3
``` 

Do you have any idea where these p2fetch entries are defined?

**Comment by maggu2810** [comment]
Certain bundles used by Xtext are not available on JCenter of Maven Central but on a p2 eclipse repository.
I created a "p2fetch" project that contains pom only to fetch a bundle from p2 and deploy it to a maven repo. The p2fetch stuff is part of my maven repo on bintray.
To get Xtext working, we need that bundles on a maven repo to fetch them using some GAV.
The namespace that contains "playground" is an old one und should not be used anymore.
Xtext is part of the target platform definition and so you find it in the shk feature file.

**Pull request merged**
