### PR TITLE
Support newer Eclipse versions

### LINKED ISSUE #1423: Eclipse installation fails due to incompatible plug-ins
The Eclipse Oomph installer fails for newer Eclipse versions like 2022-12 because some Eclipse plug-ins are no longer compatible:

# Broken plug-ins

## :x: Mylyn (`org.eclipse.mylyn.*.feature.group` requirements)

**Since:** Eclipse 2022-06

**Logging:**

```
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1669561710648
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1669561710648 requires 'org.eclipse.equinox.p2.iu; org.eclipse.mylyn.java_feature.feature.group 0.0.0' but it could not be found
```

Looks like this plug-in is no longer part of the Eclipse release train and is being restructured.

**See also:** [Mylyn not working with eclipse 2022-06](https://bugs.eclipse.org/bugs/show_bug.cgi?id=580257)

Most likely we can just remove these requirements.

---

## :x: M2E Sourcelookup (`bjmi.m2e.sourcelookup.feature.feature.group` requirement)

**Since:** Eclipse 2022-09

**Logging:**

```
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1669561905048
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: M2E Sourcelookup 1.1.6.v20170717-044847 (bjmi.m2e.sourcelookup 1.1.6.v20170717-044847) requires 'osgi.bundle; org.eclipse.m2e.core [1.1.0,2.0.0)' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1669561905048
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; bjmi.m2e.sourcelookup.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: M2E Sourcelookup 1.1.6.v20170717-044847 (bjmi.m2e.sourcelookup.feature.feature.group 1.1.6.v20170717-044847)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; bjmi.m2e.sourcelookup [1.1.6.v20170717-044847,1.1.6.v20170717-044847]
```

Eclipse 2022-12 ships with org.eclipse.m2e.core 2.0.4.20221115-1709 so this plug-in needs to be updated for this dependency change.

The GitHub repo was recently archived: https://github.com/bjmi/m2e.sourcelookup
Perhaps someone will fork it to create a fix.

---

## :heavy_check_mark: Eclipse External Annotations (EEA) m2e plugin (`org.lastnpe.m2e.feature.feature.group` requirement)

**Since:** Eclipse 2022-09

**Logging:**

```
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1669562279310
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: eclipse-external-annotations-m2e-plugin 1.0.0.201810042020 (org.lastnpe.m2e.core 1.0.0.201810042020) requires 'osgi.bundle; org.eclipse.m2e.maven.runtime [1.6.0,2.0.0)' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1669562279310
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.lastnpe.m2e.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: eclipse-external-annotations-m2e-plugin 1.0.0.201810042020 (org.lastnpe.m2e.feature.feature.group 1.0.0.201810042020)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.lastnpe.m2e.core [1.0.0.201810042020,1.0.0.201810042020]
```

Eclipse 2022-12 ships with org.eclipse.m2e.maven.runtime 3.8.602.20221112-1947 so this plug-in needs to be updated for this dependency change.

**See also:** https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/issues/47

---

## :heavy_check_mark: m2e connector for build-helper-maven-plugin (`org.sonatype.m2e.buildhelper.feature.feature.group` requirement)

**Since:** Eclipse 2022-09

**Logging:**

```
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1669562551086
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: m2e connector for build-helper-maven-plugin 0.15.0.201207090124 (org.sonatype.m2e.buildhelper 0.15.0.201207090124) requires 'osgi.bundle; org.eclipse.m2e.jdt [1.1.0,2.0.0)' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1669562551086
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.sonatype.m2e.buildhelper.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: m2e connector for build-helper-maven-plugin 0.15.0.201207090124 (org.sonatype.m2e.buildhelper.feature.feature.group 0.15.0.201207090124)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.sonatype.m2e.buildhelper [0.15.0.201207090124,0.15.0.201207090124]
```

Eclipse 2022-12 ships with org.eclipse.m2e.jdt 2.0.2.20221118-1906 so this plug-in needs to be updated for this dependency change.

There is a fork that works with newer Eclipse versions: https://github.com/tesla/m2eclipse-buildhelper/

# Workarounds

* Select Eclipse 2022-03 (or older) during installation (https://github.com/openhab/openhab-docs/pull/1925)

image

* Use Oomph configuration file that does not install these plug-ins

  As a test I've adapted the Oomph configuration file in https://raw.githubusercontent.com/wborn/openhab-distro/fix-oomph/launch/openHAB2.setup so it doesn't install these plug-ins.
  
  You can add an additional configuration file during installation like this:
  
  
eclipse

### PR DESCRIPTION
**Pull request by wborn**
* Remove bjmi.m2e.sourcelookup.feature.feature.group requirement
* Remove org.eclipse.mylyn.*.feature.group requirements
* Update org.lastnpe.m2e.feature.feature.group repository URL
* Update org.sonatype.m2e.buildhelper.feature.feature.group repository URL
* Use pom packaging to prevent errors when launching Demo app

Fixes #1423

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Excellent, thank you!

**Comment by kaikreuzer** [comment]
@wborn I've just tried to set up a new IDE with Eclipse 2023-03.
Installation all works well, but if I try to run or debug the demo app, the bndrun launcher starts, keeps consuming more and more CPU and nothing happens... I cannot get the openHAB instance being started. 😢 
Is this currently working for you? I am out of ideas what I can analyze in order to figure out the cause for this...

**Comment by wborn** [comment]
Yes it still works for me with Eclipse 2023-03 if I resolve the runbundles like #1520.

> if I try to run or debug the demo app, the bndrun launcher starts, keeps consuming more and more CPU and nothing happens.

There were also similar issues before this upgrade, see: 

https://community.openhab.org/t/starting-demo-app-takes-ages-10-12min-on-every-run-osgi-startup/122083

**Comment by kaikreuzer** [comment]
#1520 unfortunately didn't help in my case.
Thanks for the link to the forum - happy to see that I am not the only one with that issue recently. Will try to follow up with the others there...

**Pull request merged**
