### PR TITLE
Add update instructions for breaking Windcentrale Binding changes

### PR DESCRIPTION
**Pull request by wborn**
Related to openhab/openhab-addons#14770

### CODE REVIEW

**Review by J-N-K — APPROVED** [review]
Thanks!

**Comment by jlaur** [comment]
@wborn - should we move this note as well as #1523 to a new `[3.4.4]` section now that we are breaking them already in next hotfix with openhab/openhab-addons#14812 and openhab/openhab-addons#14820?

**Comment by wborn** [comment]
Yes we should probably move such backports in the list on the main branch and add also add them to the list in the 3.4.x branch.

**Comment by wborn** [comment]
When 3.4.4 is released can also update the docs for the breaking changes like described in https://github.com/openhab/openhab-addons/issues/14049#issuecomment-1502160824.

**Pull request merged**
