### PR TITLE
different improvements

### PR DESCRIPTION
**Pull request by maggu2810**
* The USB discovery consumer can be removed as long as there is also no provider in the default launch configuration.
* Bump target platform to Photon
* ~As long as jUPnP does not declare that it provides the JUPnPService I added a simple workaround. If the commits are kept separated, this can be removed (reverted) later easily, if resolved upstream.~
* ~There is currently a warning about some Equinox bundles. This is caused because they are selected twice using different versions.~

### CODE REVIEW

**Comment by maggu2810** [comment]
>    * There is currently a warning about some Equinox bundles. This is caused because they are selected twice using different versions.

If you never seen this message, it could be caused because I installed "core" and "addons" in one IDE.
Then we need to consider if the chosen version of the Equinox bundles has been the correct one.

**Comment by kaikreuzer** [comment]
> As long as jUPnP does not declare that it provides the JUPnPService I added a simple workaround.

Feel free to remove it again, now that there's a JUPnP 2.5.2 with that fix available.

**Comment by maggu2810** [comment]
I used only one change for the moment, the removal of the USB discovery stuff as long as there is no provider in the launch configuration.
As soon as the provider is added there will be no warning at all...

**Comment by maggu2810** [comment]
For the multiple equinox bundles with different versions, I will first try to install an IDE with the addons only and check which version is used there.
After that I will compare with core + addons and create a appropriate fix (another PR).

**Comment by maggu2810** [comment]
I updated the Targetplatform to consume Photon instead of Oxygen (mainly because of Equinox).

This includes an update of ohdr from 1.0.39 to 1.0.40 and so requires https://github.com/openhab/openhab-deps-repo/pull/11 first.

I checked using the local build ohdr repo and the addons Eclipse IDE.

**Comment by maggu2810** [comment]
Will have a look at. But it did yesterday using the local 1.0.40 one and the bump.
Will ping you...

**Comment by maggu2810** [comment]
@kaikreuzer The IDE drives me crazy.
I have not seen the error yesterday.
I have seen the error the last hour.
I do not see the error at the moment.

Here a screenshot:
screenshot_20190223_231205

**Comment by maggu2810** [comment]
@kaikreuzer Can you give this diff a try in your local working copy:

```
diff --git a/launch/openhab.target b/launch/openhab.target
index db4e994..4dfd2da 100644
--- a/launch/openhab.target
+++ b/launch/openhab.target
@@ -1,4 +1,4 @@
-<?xml version="1.0" encoding="UTF-8" standalone="no"?><?pde version="3.8"?><target name="openHAB Target Platform" sequenceNumber="194">
+<?xml version="1.0" encoding="UTF-8" standalone="no"?><?pde version="3.8"?><target name="openHAB Target Platform" sequenceNumber="195">
 <locations>
 <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
 <unit id="net.minidev.accessors-smart" version="0.0.0"/>
@@ -43,8 +43,6 @@
 <repository location="http://eclipse.github.io/smarthome/third-party/target/repository"/>
 </location>
 <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
-<unit id="org.eclipse.equinox.sdk.feature.group" version="3.14.0.v20180518-2029"/>
-<unit id="org.eclipse.jdt.feature.group" version="3.14.0.v20180611-0500"/>
 <repository location="https://download.eclipse.org/releases/photon"/>
 </location>
     <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
@@ -215,8 +213,9 @@
     <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
         <unit id="org.openhab.deps.runtime.feature.group" version="1.0.40"/>
         <unit id="org.openhab.deps.test.feature.group" version="1.0.40"/>
-        <repository location="https://dl.bintray.com/openhab/p2/openhab-deps-repo/1.0.40"/>
+        <repository location="file:///home/maggu2810/data/shared/bin/pkgs/eclipse/oh.git/openhab-deps-repo/p2/org.openhab.deps.repository/target/repository"/>
     </location>
 </locations>
 <targetJRE path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
-</target>
\ No newline at end of file
+</target>
+
```

**Comment by maggu2810** [comment]
@kaikreuzer Can you give the following changes a try in your local working copy:

```diff
diff --git a/launch/openhab.target b/launch/openhab.target
index db4e994..a18c54e 100644
--- a/launch/openhab.target
+++ b/launch/openhab.target
@@ -1,4 +1,4 @@
-<?xml version="1.0" encoding="UTF-8" standalone="no"?><?pde version="3.8"?><target name="openHAB Target Platform" sequenceNumber="194">
+<?xml version="1.0" encoding="UTF-8" standalone="no"?><?pde version="3.8"?><target name="openHAB Target Platform" sequenceNumber="195">
 <locations>
 <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
 <unit id="net.minidev.accessors-smart" version="0.0.0"/>
@@ -43,8 +43,6 @@
 <repository location="http://eclipse.github.io/smarthome/third-party/target/repository"/>
 </location>
 <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
-<unit id="org.eclipse.equinox.sdk.feature.group" version="3.14.0.v20180518-2029"/>
-<unit id="org.eclipse.jdt.feature.group" version="3.14.0.v20180611-0500"/>
 <repository location="https://download.eclipse.org/releases/photon"/>
 </location>
     <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
```

**Comment by maggu2810** [comment]
I added a commit with that change.

**Comment by kaikreuzer** [comment]
@maggu2810 I enabled test execution on openhab2-addons PR build yesterday and since then they are all failing with errors like:
```
[INFO] --- tycho-surefire-plugin:1.2.0:test (default-test) @ org.openhab.binding.astro.test ---
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.core.runtime 3.14.0.v20180417-0825
[ERROR]   Missing requirement: org.eclipse.core.runtime 3.14.0.v20180417-0825 requires 'osgi.bundle; org.eclipse.equinox.registry [3.8.0,4.0.0)' but it could not be found
```
(see e.g. https://ci.openhab.org/job/PR-openHAB2-Addons/12750/console).
Seems to be related to the TP changes.

Any good idea how to best fix this?

**Comment by maggu2810** [comment]
If it is related to my TP changes, I will have a look at.
You are sure that it worked before my changes?

Because then it should be easy as it indicates that the features "org.openhab.deps.runtime.feature.group"  and / or "org.openhab.deps.test.feature.group" are not really complete and we need to add some bundles that has been added by "org.eclipse.equinox.sdk.feature.group" or "org.eclipse.jdt.feature.group".

**Comment by kaikreuzer** [comment]
I cannot promise to 100% that it was working before, but I am almost pretty certain that it did.

**Comment by maggu2810** [comment]
The `org.eclipse.equinox.registry` one can be solved easily.
But then another one is identified.

org.openhab.core.test is using hamcrest in a non splitted manner.
The test execution runtime on openhab2-addons depends on hamcrest split packages.

This will not work -- at least I don't succeed to solve it and I don't want to invest more time...

The problem should be solved while migration from Tycho + Maven to Bnd + Maven.

**Comment by kaikreuzer** [comment]
> The problem should be solved while migration from Tycho + Maven to Bnd + Maven.

This can still take a while - until then, any user that works on a binding will come across this issue when executing a local Maven build and might wonder, what he did wrong ( see e.g. [here](https://community.openhab.org/t/about-hmtl-missing-with-mvn-clean-install-2-5/69210?u=kai)). Not sure we should really declare the master branch broken until ALL migration to bnd is done?

**Comment by maggu2810** [comment]
My understanding has been it is about test execution at build time.
So instead of declaring the master branch broken, test modules can be commented and the local build will succeed.

**Comment by maggu2810** [comment]
As written in my comment before, the missing registry bundle is caused by my p2 repo changes.
I can fix that.

But it will not make the tests working.

**Comment by maggu2810** [comment]
I gave it a try for the AVM FRITZ! Binding Tests.
I migrated the test only to Maven + Bnd while keeping the tested bundle a Maven + Tycho one.
It works and it took about 5 minutes (sure, other ones could be more complicated, but I don't think so for addons).

**Pull request merged**
