### PR TITLE
Override default console highlighting colors

### PR DESCRIPTION
**Pull request by BClark09**
## PuTTY

image

## Powershell.exe

image

## Debian terminal

image

## Debian terminal (Black on white scheme)

image

Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I like it - let's wait for some other opinions, though :-)

**Comment by BClark09** [comment]
Just for info, this is what PuTTY looks like without the change:

image

A couple of thoughts,

1. variable names should be in the system default font color, it's a bit hard to read on the light background.

2. The original colors had strings and numbers the same color, we could probably keep this as an option.

WDYT?

**Comment by martinvw** [comment]
I only think that the dark green '0' in the example is not that readable

**Comment by kaikreuzer** [comment]
What is the difference between "123" and "0" so that the first is light and the second dark green?

**Comment by BClark09** [comment]
I believe the '0' at the end is something that Karaf adds at the end as a suggestion to close off the command. It is set using the 're' key. (for Repair). It will also add a quote as a suggestion to end an open quote. I can change this to yellow?

**Comment by CWempe** [comment]
Looks good to me.

I think we should not change to much.

**Comment by martinvw** [comment]
Okay thanks guys!

**Pull request merged**
