### PR TITLE
changes for Xtext 2.9.2 usage (ESH / OH)

### PR DESCRIPTION
**Pull request by maggu2810**
Related to: https://github.com/eclipse/smarthome/pull/1383

### CODE REVIEW

**Comment by maggu2810** [comment]
A SNAPSHOT of the offline distribution for testing could be downloaded here: https://drive.google.com/open?id=0Bx99QXY8p6gvNmNFd2dRM21vd0k

**Comment by maggu2810** [comment]
I see this on startup of openHAB (IIRC not always).

```text
11:33:12.084 [ERROR] [xbase.resource.BatchLinkableResource] - resolution of uriFragment '|123' failed.
java.lang.IndexOutOfBoundsException: Index: 123, Size: 6
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)[:1.8.0_74]
	at java.util.ArrayList.get(ArrayList.java:429)[:1.8.0_74]
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.hasLazyProxyInformation(LazyLinkingResource.java:502)[132:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getLazyProxyInformation(LazyLinkingResource.java:509)[132:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getLazyProxyInformation(LazyURIEncoder.java:148)[132:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.decode(LazyURIEncoder.java:127)[132:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:113)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)[61:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:199)[61:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259)[61:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)[61:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.getFeature(XAbstractFeatureCallImplCustom.java:48)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.ensureFeatureLinked(XAbstractFeatureCallImplCustom.java:135)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.impl.XFeatureCallImplCustom.isTypeLiteral(XFeatureCallImplCustom.java:60)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:859)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:223)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluateArgumentExpressions(XbaseInterpreter.java:1115)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._invokeFeature(XbaseInterpreter.java:1045)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeFeature(XbaseInterpreter.java:991)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.smarthome.model.script.interpreter.ScriptInterpreter.invokeFeature(ScriptInterpreter.java:114)[120:org.eclipse.smarthome.model.script:0.8.0.201604140722]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:901)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:864)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:223)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:446)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:227)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluate(XbaseInterpreter.java:189)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.smarthome.model.script.runtime.internal.engine.ScriptImpl.execute(ScriptImpl.java:77)[121:org.eclipse.smarthome.model.script.runtime:0.8.0.201604140722]
	at org.eclipse.smarthome.model.script.engine.ScriptExecutionThread.run(ScriptExecutionThread.java:42)[120:org.eclipse.smarthome.model.script:0.8.0.201604140722]
```

```text
11:33:12.094 [ERROR] [xbase.resource.BatchLinkableResource] - resolution of uriFragment '|123' failed.
java.lang.IndexOutOfBoundsException: Index: 123, Size: 119
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)[:1.8.0_74]
	at java.util.ArrayList.get(ArrayList.java:429)[:1.8.0_74]
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.hasLazyProxyInformation(LazyLinkingResource.java:502)[132:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getLazyProxyInformation(LazyLinkingResource.java:509)[132:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getLazyProxyInformation(LazyURIEncoder.java:148)[132:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.decode(LazyURIEncoder.java:127)[132:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:113)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)[61:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:203)[61:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259)[61:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)[61:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.getFeature(XAbstractFeatureCallImplCustom.java:48)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.ensureFeatureLinked(XAbstractFeatureCallImplCustom.java:135)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.impl.XFeatureCallImplCustom.isTypeLiteral(XFeatureCallImplCustom.java:60)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:859)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:223)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluateArgumentExpressions(XbaseInterpreter.java:1115)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._invokeFeature(XbaseInterpreter.java:1045)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeFeature(XbaseInterpreter.java:991)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.smarthome.model.script.interpreter.ScriptInterpreter.invokeFeature(ScriptInterpreter.java:114)[120:org.eclipse.smarthome.model.script:0.8.0.201604140722]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:901)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:864)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:223)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:446)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:227)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluate(XbaseInterpreter.java:189)[136:org.eclipse.xtext.xbase:2.9.2]
	at org.eclipse.smarthome.model.script.runtime.internal.engine.ScriptImpl.execute(ScriptImpl.java:77)[121:org.eclipse.smarthome.model.script.runtime:0.8.0.201604140722]
	at org.eclipse.smarthome.model.script.engine.ScriptExecutionThread.run(ScriptExecutionThread.java:42)[120:org.eclipse.smarthome.model.script:0.8.0.201604140722]
```

**Comment by kaikreuzer** [comment]
Many thanks @maggu2810, this looks really good - I tested it with the standard packaging and deployed the demo afterwards; this makes things more reliable (as it avoids bugs that we already have seen on the old version).

I would say that your PRs are ready to be merged, unless you want to do something more.

**Comment by maggu2810** [comment]
Let's merge. IMHO it is better to work on that base if its merged to master because there are "all" repositories involved. The merge request builder fails because of that, too.

**Comment by kaikreuzer** [comment]
I now have many entries like this on startup:
```
19:43:38.447 [WARN ] [ce.jetty.internal.JettyServerWrapper] - failed to parse and instantiate of javax.servlet.ServletContainerInitializer in classpath
19:43:39.822 [WARN ] [ce.jetty.internal.JettyServerWrapper] - failed to parse and instantiate of javax.servlet.ServletContainerInitializer in classpath
19:43:44.634 [WARN ] [ce.jetty.internal.JettyServerWrapper] - failed to parse and instantiate of javax.servlet.ServletContainerInitializer in classpath
19:43:46.635 [WARN ] [ce.jetty.internal.JettyServerWrapper] - failed to parse and instantiate of javax.servlet.ServletContainerInitializer in classpath
```
Any idea what can cause this?

**Comment by maggu2810** [comment]
Perhaps @dvanherbergen does know anything about that:
https://github.com/hstaudacher/osgi-jax-rs-connector/issues/131

**Comment by kaikreuzer** [comment]
Yeah, he might - for the moment I might reconfigure the logging, so that this is suppressed (and we do not get too many user reports for it)

**Comment by kaikreuzer** [comment]
> for the moment I might reconfigure the logging, so that this is suppressed

Hm, I am somehow failing to do so... the log messages still appear.

**Comment by maggu2810** [comment]
Add the following line to this file <code>runtime/karaf/etc/org.ops4j.pax.logging.cfg</code>

```text
log4j.logger.org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper = ERROR
```

**Pull request merged**
