### PR TITLE
Encryption of karaf passwords

### PR DESCRIPTION
**Pull request by EliasGabrielsson**
Signed-off-by: Elias Gabrielsson <elias@benefactory.se>

### CODE REVIEW

**Comment by EliasGabrielsson** [comment]
Do I need to to do additional things then just add the file to this folder to have it installed?

**Comment by kaikreuzer** [comment]
Not 100% sure if Karaf distro packaging itself might create that file as well. Best if you simply run the build and check the result, if it does what you expect.

**Comment by EliasGabrielsson** [comment]
Need some additionally direction to proceed, see:
https://community.openhab.org/t/how-to-build-zip-release-for-oh2/20182

**Comment by kaikreuzer** [comment]
Answered!

**Comment by EliasGabrielsson** [comment]
@kaikreuzer Confirmed working, ready for merge.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
