### PR TITLE
Keep logging of performance data enabled when debugging

### PR DESCRIPTION
**Pull request by fwolter**
Signed-off-by: Fabian Wolter <github@fabian-wolter.de>

### CODE REVIEW

**Review by kaikreuzer — COMMENTED** [review]
Thanks.
Would you find a way to do it without touching the `karaf` file? Afaik, we do not customize it so far, which means that such changes might get easily lost with the next Karaf upgrade.

I see that Karaf does not have any variable for specific non-debug parameters, so it might not be easy to solve, though.

**Comment by fwolter** [comment]
The karaf script executes the setenv script before the debug parameters are processed. `start.sh` and `start_debug.sh` are not used when using systemd. I slept over it, but no solution came to my mind without touching the karaf file.

**Comment by kaikreuzer** [comment]
@wborn As you are our "Karaf upgrade master": Would you have any good recommendation on how to proceed here?

**Comment by wborn** [comment]
> Would you have any good recommendation on how to proceed here?

It is easy for such changes to get lost when upgrading Karaf the next time. So to prevent that from happening it's probably best to add some comments to those lines to clearly indicate that those are openHAB customizations.

**Comment by fwolter** [comment]
Done

**Review by kaikreuzer — APPROVED** [review]
Thank you!
And now you could try to do a PR against https://github.com/apache/karaf, maybe then we won't need to merge our customizations when upgrading anymore 😎 .

**Comment by fwolter** [comment]
Done apache/karaf#1261

**Comment by fwolter** [comment]
The karaf PR has been merged.

**Pull request merged**
