### PR TITLE
added fsinternetradio binding

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by dvanherbergen** [comment]
Adding this feature causes my build to fail with:
```
Unable to resolve org.eclipse.smarthome.binding.fsinternetradio/0.8.0.201601082217: missing requirement [org.eclipse.smarthome.binding.fsinternetradio/0.8.0.201601082217] osgi.wiring.package; filter:="(osgi.wiring.package=org.jupnp.model.meta)"]]
```

**Comment by kaikreuzer** [comment]
Wait for this to be finished, then it will be green - but you are right, please do not merge before the ESH build is available in the maven repo.

**Comment by dvanherbergen** [comment]
I did do a local smarthome build with the latest changes first. The build had a little hiccup on the automation part, but then I continued the rest of the build, so I was expecting the distro to build correctly locally. Did you do a local build that passed?

**Comment by kaikreuzer** [comment]
Yes, I did.

**Comment by dvanherbergen** [comment]
OK, maybe I should do a clean first. I'll try again.

**Comment by dvanherbergen** [comment]
New build is available in maven repo and build works like a charm after a clean.

**Pull request merged**
