### PR TITLE
Custom dynamic icons: default file required

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: lolodomo lg.hc@free.fr

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks, could you please also sign-off your commit?

**Comment by lolodomo** [comment]
For number item, I have a doubt: is it required to have an icon for each possible value ?
I can see icons defined for 10 20 30 ... 100 and not 1 2 3 ... 99 100.
In this case, my added sentence has to be updated.

And we should add something about SVG format required for Basic UI if it is really a requirement.

**Comment by kaikreuzer** [comment]
>  is it required to have an icon for each possible value ?
No, see https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui.icon/src/main/java/org/eclipse/smarthome/ui/icon/AbstractResourceIconProvider.java#L22

> And we should add something about SVG format required for Basic UI if it is really a requirement.

Just like for the Classic UI, you can configure what to use:
https://github.com/openhab/openhab-distro/blob/master/features/openhab-demo-resources/src/main/resources/services/classicui.cfg#L5
https://github.com/openhab/openhab-distro/blob/master/features/openhab-demo-resources/src/main/resources/services/basicui.cfg#L5

But it is right that the default setting for the Basic UI is SVG, so feel free to add a word of warning in the migration doc.

**Comment by lolodomo** [comment]
Ok,explanations enhanced in the migration documentation.

**Comment by kaikreuzer** [comment]
Thanks - I am still waiting for the sign-off on your commit(s). Could you please squash and sign them? I'll then merge. Thanks!

**Comment by lolodomo** [comment]
I added a signed-off-by in first message. Is it not what you ask for ? If not, I need explanations of what to do.
I will sqush the 2 changes later today.

**Comment by kaikreuzer** [comment]
The sign-off needs to be on the commit, not the PR. See https://github.com/openhab/openhab-distro/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by umiddelb** [comment]
> If not, I need explanations of what to do

Just issue: 
```
git commit --amend -s --no-edit && git push -f
```
to amend the last commit.

**Comment by lolodomo** [comment]
My 2 commits habe been squashed and signed-off.

**Comment by kaikreuzer** [comment]
Perfect, thanks!

**Pull request merged**
