### PR TITLE
Moved https://github.com/openhab/openhab2-addons/pull/579

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@dvanherbergen @maggu2810 Is there any reason to not merge this?

**Comment by dvanherbergen** [comment]
I don't see any issues with it.

**Comment by kaikreuzer** [comment]
So why don't you merge it? :-)

**Comment by dvanherbergen** [comment]
> Pull requests that have a failing status can’t be merged from a phone

It doesn't let me ;-)

Will merge later when using a pc.

**Comment by maggu2810** [comment]
If something goes wrong, blame me -- I pressed "merged". :wink:

**Pull request merged**
