### PR TITLE
added ESH version of Homematic binding to distro

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by martinvw** [comment]
Feel free to wait for Jenkins :-)

**Comment by kaikreuzer** [comment]
Jenkins loves it ;-)

**Comment by wborn** [comment]
Thank you all. :-)

**Comment by kaikreuzer** [comment]
Hm, it isn't as good as I thought:

```
17:16:46.049 [ERROR] [.core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-homematic': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-homematic; type=karaf.feature; version="[2.4.0.SNAPSHOT,2.4.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-homematic)(type=karaf.feature)(version>=2.4.0.SNAPSHOT)(version<=2.4.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-homematic/2.4.0.SNAPSHOT: missing requirement [openhab-binding-homematic/2.4.0.SNAPSHOT] osgi.identity; osgi.identity=esh-binding-homematic; type=karaf.feature]
```

I have created https://github.com/eclipse/smarthome/pull/5820, which will hopefully fix it.

**Comment by kaikreuzer** [comment]
FTR: I have reverted this change for now as https://github.com/eclipse/smarthome/pull/5820 is still open and the ESH build currently has major issues (probably due to server load through Photon).

**Pull request merged**
