### PR TITLE
Added message for satel binding

### PR DESCRIPTION
**Pull request by druciak**
Related to https://github.com/openhab/openhab-addons/pull/7282

Signed-off-by: Krzysztof Goworek <krzysztof.goworek@gmail.com>

### CODE REVIEW

**Comment by druciak** [comment]
@J-N-K could you please look into this PR?

**Comment by J-N-K** [comment]
I can look, but I can’t merge over here.

**Comment by druciak** [comment]
@kaikreuzer I hope you can :-)

**Comment by druciak** [comment]
Thank you!

**Pull request merged**
