### PR TITLE
Add --non-interactive CLI argument to backup script, enabling backups from GUI

### PR DESCRIPTION
**Pull request by robclark56**
See more details here.
https://community.openhab.org/t/when-will-backup-restore-be-in-openhab-gui/112816/11

### CODE REVIEW

**Comment by BClark09** [comment]
Hi @robclark56,

The change is a good idea but what you've suggested forces specific paths to be used. You can be more general and add a "--non-interactive" option that simply skips the prompts. That way, what you've implemented can be done with:

```
./backup --non-interactive <path>
```

**Comment by robclark56** [comment]
Updated with changes recommended by @BClark09

**Review by kaikreuzer — APPROVED** [review]
Many thanks and sorry for the delayed merge!

**Comment by kaikreuzer** [comment]
Argh, well, I actually cannot merge, because the DCO check fails.
@robclark56 Could you please add a sign-off (either to your commits or as a comment here on the PR, which I'll then attach to your squashed commits). Thanks!

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
