### PR TITLE
enabled Equinox compatibility mode for boot delegation

### LINKED ISSUE #85: Enable boot delegation for backward compatibility
Moving from plain Equinox in alpah2 to Karaf in beta1 is causing many problems, specifically with openHAB 1 add-ons, see e.g.
https://community.openhab.org/t/error-on-weather-binding-when-starting-openhab2/6081
https://community.openhab.org/t/avm-fritz-box-binding-oh2b1-issue/6321
https://community.openhab.org/t/tellstick-binding-for-openhab2/1582/14
https://community.openhab.org/t/we-need-your-help-on-testing/298/29

and many more. This is very annoying since all of this used to work smoothly before.

Many of the issues seem to be due to the fact that JDK classes such as javax.xml are not on the bootclasspath. I wonder if this can be changed for the sake of backward compatibility (knowing that it is no the "clean osgi way")?

To our Karaf experts @dvanherbergen, @maggu2810, @anierbeck, @cschneider: Do you have a suggestion what we should do?

### PR DESCRIPTION
**Pull request by kaikreuzer**
see https://wiki.eclipse.org/Equinox_Boot_Delegation
resolves #85

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@dvanherbergen, @maggu2810 - ok to merge?

**Comment by dvanherbergen** [comment]
OK for me (although I haven't tested it)

**Comment by kaikreuzer** [comment]
I tested it and it seemed to resolve some issues - so let's give it a try.

**Comment by maggu2810** [comment]
All fine with me.

**Pull request merged**
