### PR TITLE
Helper scripts for bintray.

### PR DESCRIPTION
**Pull request by theoweiss**
Signed-off-by: Theo Weiss <theo@m1theo.org> (github: theoweiss)

### CODE REVIEW

**Comment by theoweiss** [comment]
I've created the apt-repo2 repository and added the fake packages for version 2.0.0b3.
For uploading the openHAB distro files step into the distributions/distribution-resources/src/main/resources/bin directory and execute bintray-upload-debs.sh with the arguments: 
`./bintray-upload-debs.sh openhab <bintray-api-key> <gpg-secret> 2.0.0b3 testing`

The repo can be used by adding this line to the apt-sources-list:
`deb https://dl.bintray.com/openhab/apt-repo2 testing main`

Install openHAB2 with:
`
apt-get update &&
apt-get install openhab2-offline (or openhab2-online)
`

**Comment by theoweiss** [comment]
@kaikreuzer how should we proceed? For openhab(1) @teichsta used this kind of scripts for publishing the deb packages.

**Comment by kaikreuzer** [comment]
Sorry, was travelling this week, so this didn't yet get my attention.
Can we do a beta3 package upload, although we did not have the Debian PR merged in the beta3 tag?
Can you take care of that? Would be awesome!

**Comment by theoweiss** [comment]
> Can we do a beta3 package upload, although we did not have the Debian PR merged in the beta3 tag?
No, the Debian PR changes are needed. 
As far as I can see, until now there only two minor documentation and configuration changes since beta3 plus  the deb packaging changes. A build of the current HEAD (and a tag beta3deb?) should be fine.

**Comment by kaikreuzer** [comment]
No, current HEAD does not work as it would draw in snapshots from ESH, OH1 and OH2.
So you should use https://github.com/openhab/openhab-distro/commit/8073dfcb2ce33bb3932e945e48702ecebda5c2a3 and cherry-pick the debian PR.

**Comment by theoweiss** [comment]
Ok. I'll give it a try. Here's my branch with the cherries picked: https://github.com/theoweiss/openhab-distro/tree/b3debRelease

**Comment by kaikreuzer** [comment]
Looks good to me!

**Comment by theoweiss** [comment]
I did a `mvn clean install` on my mac and got an openhab2-online-2.0.0.b3.deb and an openhab2-offline-2.0.0.b3.deb package. Should I upload these packages to bintray?

**Comment by kaikreuzer** [comment]
Go ahead!

**Comment by theoweiss** [comment]
The packages are online. I will now test the repo. 
We will need some docs for the debian installation procedure. Where should they go to?

**Comment by kaikreuzer** [comment]
I'll publish tomorrow a major update of the documentation website - once it is there, I will give you a link to where it should go!

**Comment by theoweiss** [comment]
Fine.

I've tested installation on a raspi 3 with raspian jessy: looks good to me.
The sources list entry is:
`deb https://dl.bintray.com/openhab/apt-repo2 testing main`

**Comment by kaikreuzer** [comment]
Ok, here we go: The documentation should go to https://github.com/openhab/openhab-docs/blob/gh-pages/_source/installation/apt.md.

You can find details on how to contribute to the documentation right here: https://github.com/openhab/openhab-docs#contributing-to-the-documentation

**Comment by tavalin** [comment]
Will this allow for installing a daily snapshot version through apt-get? Or is this only for specific releases?

**Comment by zephod77** [comment]
Where can I find the public key for this repo?

**Comment by theoweiss** [comment]
@tavalin as far as I know there are no daily snapshots. But you can install the latest build from cloudbees like described here: https://github.com/openhab/openhab-distro/issues/66#issuecomment-221108805

**Comment by theoweiss** [comment]
@zephod77 the key is the same as for openhab(1) see https://github.com/openhab/openhab/wiki/Linux-and-OS-X#installation . 
The docs for openhab2 are in preparation.

**Comment by zephod77** [comment]
Got it - thanks. Installed OK.

**Comment by pflodo** [comment]
Excellent... Installed on plain Debian on an Intel NUC

for reference, here are the commands I gathered from above and used:
```
wget -qO - 'https://bintray.com/user/downloadSubjectPublicKey?username=openhab' | sudo apt-key add -
echo "deb https://dl.bintray.com/openhab/apt-repo2 testing main" | sudo tee /etc/apt/sources.list.d/openhab.list
apt-get install apt-transport-https    
apt-get update && apt-get install openhab2-online

```

**Comment by theoweiss** [comment]
@kaikreuzer I'm struggling with the markdown. Jekyll needs a different markdown than GFM. If I copy and paste the current wiki page it looks really ugly. Any hints?

**Comment by kaikreuzer** [comment]
I think the main hint is that you need empty lines before and after each code block - this is not required on the wiki, but for Jekyll. If you add these lines, it usually immediately looks much nicer!

**Comment by theoweiss** [comment]
@kaikreuzer the PR for the docs is online.

**Comment by kaikreuzer** [comment]
Thanks @theoweiss, it is online now: http://docs.openhab.org/installation/apt.html

**Pull request merged**
