### PR TITLE
Update targetPlatform sequence number after zigbee bump

### PR DESCRIPTION
**Pull request by triller-telekom**
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by triller-telekom** [comment]
@kaikreuzer @martinvw Please merge ASAP because the platform does not resolve correctly in the IDE at the moment.

**Comment by HerzScheisse** [comment]
Thanks @triller-telekom @martinvw 
I'm not experienced enough to say if this was related to my issue in the OH Comm (linked above) but this seems to solve the problem... it is working now...

**Comment by triller-telekom** [comment]
Actually your issue was not directly related to this. Your issue was because there were some artifacts missing in a p2 repository which was also updated yesterday around lunch time by @kaikreuzer :)

**Comment by HardLR** [comment]
@triller-telekom I think so , How to solve it?

**Comment by triller-telekom** [comment]
@HardLR Sorry I don't get your question. Also this is a merged PR, if you have a problem, please create a new issue for it and explain it. Thanks.

**Pull request merged**
