### PR TITLE
Adding upgrade notes on compatibility break for PR (3264)

### PR DESCRIPTION
**Pull request by zarusz**
Updating notes to correspond with PR [3264](https://github.com/openhab/openhab2-addons/pull/3264)

Signed-off-by: Tomasz Maruszak <maruszaktomasz@gmail.com>

### CODE REVIEW

**Comment by martinvw** [comment]
@BClark09 is this the way it is intended or is this text maybe too long?

**Comment by BClark09** [comment]
Ideally, the messages should be as short and as specific as possible. But I think we should handle the case for long messages anyway, it may be needed to give the user a good impression on what needs to be done.

Large terminals look okay IMO:
image

Narrow terminals start to get a bit hard to read:
image

I can also change the script to align the message if you believe this looks better:
image

**Comment by martinvw** [comment]
Shall we leave away some details, what would you think of:

```Changed configuration keys. For main Thing keys changed from `HOST` to `host`, `PORT` to `port`. For zone Thing keys changed from `ZONE` to `zone`. ```
 
I think it is (or at least should) always the case that the documentation contains up-to-date examples. The (technical) reason why might be less relevant.

**Comment by BClark09** [comment]
I think that would be better :)

**Comment by zarusz** [comment]
I just pushed the changed message, which is what @martinvw suggested :-)

**Comment by martinvw** [comment]
Thanks @zarusz

**Pull request merged**
