### PR TITLE
remove deb package specific addons.cfg

### PR DESCRIPTION
**Pull request by theoweiss**
This PR should solve #321
I've removed the deb package specific addons.cfg and now the unchanged file from the distro package is used.

I think I've added the deb specific addons.cfg because in early 2016 there was no default base installation package (I may be wrong). But today there is clearly a default package named "standard" and therefore we can drop the special handling for the deb packages.  

@ThomDietrich or @BClark09 could you test these new packages?

I've made a short test with the offline package. It worked so far but I got these errors, which I think are not related to my changes.

```
2016-11-13 23:32:15.471 [ERROR] [.glassfish.hk2.osgi-resource-locator] - FrameworkEvent ERROR - org.glassfish.hk2.osgi-resource-locator
org.osgi.framework.BundleException: Exception in org.apache.karaf.features.internal.service.FeaturesServiceImpl$3.end()
        at org.eclipse.osgi.internal.framework.OSGiFrameworkHooks$CoreResolverHookFactory.handleHookException(OSGiFrameworkHooks.java:164)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.OSGiFrameworkHooks$CoreResolverHookFactory$CoreResolverHook.end(OSGiFrameworkHooks.java:340)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleResolver$ResolveProcess.resolve(ModuleResolver.java:901)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleResolver.resolveDelta(ModuleResolver.java:111)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:479)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:437)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:427)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.Module.start(Module.java:416)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1498)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
2016-11-13 23:32:42.588 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2016-11-13 23:32:42.675 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2016-11-13 23:32:42.752 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /ui
2016-11-13 23:32:42.914 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2016-11-13 23:32:43.046 [INFO ] [core.karaf.internal.FeatureInstaller] - Installed 'openhab-package-standard'
```

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Ah the "glassfish" error. I know that one. Has been there for a long time, only the first time you start a fresh setup. 
Now that I mention it. Should probably have reported it at some point 🙊
Would you do that now?

**Comment by ThomDietrich** [comment]
(just approved but just based by looking at the changes)

**Comment by kaikreuzer** [comment]
Means I should merge or wait for further comments?

**Comment by BClark09** [comment]
I haven't been able to test the package yet,  but as far as I can see,  this will only prompt the user if they want to change their version of the file.  The default is "keep their own" so this should have no effect on upgrading users.  Those who change to this version will just have to specify their bindings again.

**Comment by theoweiss** [comment]
Just tested the online package and got these errors (I don't think they are related to the changes of this PR):

```
2016-11-14 00:10:22.946 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-package-standard': Error restarting bundles
2016-11-14 00:10:22.946 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-package-standard': Error restarting bundles
```

After a restart of the runtime it worked fine. It smells like running into a timeout...

**Comment by BClark09** [comment]
This PR is okay for me.

**Pull request merged**
