### PR TITLE
Add temporary patch of pax-web-jetty to avoid slow startup times.

### PR DESCRIPTION
**Pull request by dvanherbergen**
Temporary solution for #10 

Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Shall we maybe place the jar somewhere on Bintray (https://bintray.com/openhab/mvn) and include it from there? Then we would not need to have it in the source repo.

**Comment by dvanherbergen** [comment]
That would work too. We'll need to give it a different name then to indicate the patch.
I don't have upload rights to the openhab bintray. If you can deploy it there with a new name, I will update the PR to use that one.

**Comment by maggu2810** [comment]
Hm, if you use another GAV for the artifact, then you have to change the feature, to use the other one.
I think for the workaround it is ok to replace the jar file.
With this PR the bundled jar is replaced and so the feature work out of the box.

Or do I miss something?

**Comment by kaikreuzer** [comment]
I was rather thinking to only update the assembly descriptor to pick up the file as a Maven dependency than from the local project - this way, it should not have any impact on the features as the result is identical to the current PR.

**Comment by dvanherbergen** [comment]
During the assembly we could rename it back to the original name.

**Comment by maggu2810** [comment]
Ah okay.
If the assembly plugin support the reference using GAV then this is IMOH the cleaner solution.

**Comment by kaikreuzer** [comment]
Here you go: https://dl.bintray.com/openhab/mvn/org/openhab/distro/deps/pax-web-jetty/4.2.3/:pax-web-jetty-4.2.3.jar

**Comment by maggu2810** [comment]
It is up to you, but shouldn't we set the version (in the repo) to 4.2.3.sp1 or something similar to indicate it is a patched / modified 4.2.3 one?

**Comment by kaikreuzer** [comment]
https://dl.bintray.com/openhab/mvn/org/openhab/distro/deps/pax-web-jetty/4.2.3.sp1/pax-web-jetty-4.2.3.sp1.jar

Better? :-)

**Comment by dvanherbergen** [comment]
PR updated to use mvn dependency.

**Comment by kaikreuzer** [comment]
Thanks a lot!

**Comment by JSurf** [comment]
Is this fix included in the current oh beta ? I tested oh2 offline distro in a raspbian jessie/java8.openjdk based docker container on a rpi2. Host OS is arch linux. Startup times are terribly slow ~ 20 minutes for first start. If yes it does not help for me

**Comment by JSurf** [comment]
Just tried with the online distro makes no difference, startup is also painfully slow no difference to the offline distro

**Comment by dvanherbergen** [comment]
@JSurf, there is something else happening on your system. I just did a test with rpi1. The initial startup takes 8 minutes. Subsequent starts take about 3 minutes. 
Can you try installing openHAB natively, not inside a docker container?

**Comment by JSurf** [comment]
Tested outside docker environment. Seems my issues are related to my docker container/environment.
Startup times without docker seem to be Ok

**Comment by JSurf** [comment]
Turned out that openjdk on raspbian seems to be super slow. Changed to oracle jdk provided by the rpi foundation. Now startup is very fast

**Pull request merged**
