### PR TITLE
Renamed namespace "org.eclipse.smarthome" to "org.openhab.core"

### PR DESCRIPTION
**Pull request by cweitkamp**
- Renamed namespace "org.eclipse.smarthome" to "org.openhab.core"

Related to https://github.com/openhab/openhab-core/pull/1294

WIP:
- [ ] The `app.bndrun` does not include a bundle which is located outside [openhab-core](https://github.com/openhab/openhab-core).

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by cweitkamp** [comment]
Should we add REPLACE commands for the configurationPids to the [update.lst](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/update.lst)?

**Comment by kaikreuzer** [comment]
Yes, that definitely makes sense!

**Comment by vot3c** [comment]
can we still use paperui now?

**Comment by wborn** [comment]
Paper UI is removed from OH3 (master branch) @vot3c, see https://github.com/openhab/openhab-webui/pull/154.

For add-on development you can use the 2.5.x branch which has Paper UI, see also https://github.com/openhab/openhab-addons/issues/6702.

**Comment by cweitkamp** [comment]
> Should we add REPLACE / MOVE commands for the configurationPids to the `update.lst`?

I added them.

**Pull request merged**
