### PR TITLE
Fixes #114. Add fancier splash screen based on simple ascii art.

### LINKED ISSUE #114: Brand openhab console a bit more
Karaf provides capabilities to customize welcome screen when launching instance/getting there over ssh. Its very simple addon which clearly marks what kind of software user is running.

### PR DESCRIPTION
**Pull request by splatch**
This pull request provides a simple customization for shell console. 
openhab splash

### CODE REVIEW

**Comment by maggu2810** [comment]
Looks very nice.
Have you removed the trailing whitespace after 'openhab&gt;' by intention?
<code>openhab&gt;bundle:list</code> vs. <code>openhab&gt; bundle:list</code>

**Comment by kaikreuzer** [comment]
Nice! I do not like the red dots in front of "empowering" too much (makes it too many different colors for my taste). How about making them grey (as the text) or remove the line completely?

**Comment by splatch** [comment]
@maggu2810 yeah, my editor trimmed it out. WIll bring it back.
@kaikreuzer I could not find matching colors for bars from one hand and tried to refer slogan from logo. I'm fine to drop this line. These bars might not be visible when someone is using red background (I doubt if anyone does), also there is no way to make background with default color used in terminal, thus it might be tricky.

The same splash on white background
openhab splash white

With red background
openhab splash red

With silver background
openhab splash silver

**Comment by kaikreuzer** [comment]
> tried to refer slogan from logo.

Nice idea, but I think visually it is cleaner if we drop it.

**Comment by splatch** [comment]
Ammended commit. Below you can find how it looks without slogan text:

black
blue
green
navy
red
sad
silver
white
yellow

**Comment by kaikreuzer** [comment]
Cool - thanks!

**Comment by maggu2810** [comment]
@splatch :+1:

**Pull request merged**
