### PR TITLE
Upgrade to Karaf 4.2.4

### PR DESCRIPTION
**Pull request by wborn**
For Karaf 4.2.3 release notes, see:
  https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311140&version=12344587

For Karaf 4.2.4 release notes, see:
  https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12344856&projectId=12311140

---

Shoud be merged together with:

* https://github.com/openhab/openhab-core/pull/723
* https://github.com/openhab/openhab2-addons/pull/5459
* https://github.com/openhab/openhab-webui/pull/56

### CODE REVIEW

**Comment by maggu2810** [comment]
FYI: `scr:list` is broken in 4.2.4 and a fixed one is already released in 4.2.5

**Comment by kaikreuzer** [comment]
@wborn Interested in preparing a PR to upgrade to 4.2.5?

**Comment by wborn** [comment]
I already gave that a try last weekend @kaikreuzer . See my [karaf-4.2.5](https://github.com/wborn/openhab-distro/tree/karaf-4.2.5) branch. Because of [KARAF-6274](https://issues.apache.org/jira/browse/KARAF-6274) we can't update the karaf-maven-plugin to 4.2.5. Furthermore after my changes it fails to install the boot features at startup so nothing works. :disappointed: 

It throws the following exception at startup:

```
[ERROR] [nternal.service.BootFeaturesInstaller] - Error installing boot features
org.apache.karaf.features.internal.util.MultiException: Error restarting bundles:
	Exception in org.apache.felix.scr.impl.Activator.start() of bundle org.apache.felix.scr.
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1005) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1058) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:994) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
	Suppressed: org.osgi.framework.BundleException: Exception in org.apache.felix.scr.impl.Activator.start() of bundle org.apache.felix.scr.
		at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:836) ~[?:?]
		at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:765) ~[?:?]
		at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005) ~[?:?]
		at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357) ~[?:?]
		at org.eclipse.osgi.container.Module.doStart(Module.java:589) ~[?:?]
		at org.eclipse.osgi.container.Module.start(Module.java:457) ~[?:?]
		at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:431) ~[?:?]
		at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:450) ~[?:?]
		at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:161) ~[?:?]
		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1149) ~[?:?]
		at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:997) ~[?:?]
		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1058) ~[?:?]
		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:994) ~[?:?]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
		at java.lang.Thread.run(Thread.java:748) [?:?]
	Caused by: java.lang.AbstractMethodError: org.ops4j.pax.logging.log4j2.internal.PaxLoggingServiceImpl$1ManagedPaxLoggingService.getLogger(Ljava/lang/String;Ljava/lang/Class;)Lorg/osgi/service/log/Logger;
		at org.apache.felix.scr.impl.logger.R7LogServiceLogger.<init>(R7LogServiceLogger.java:35) ~[?:?]
		at org.apache.felix.scr.impl.logger.LogServiceSupport.getLogger(LogServiceSupport.java:69) ~[?:?]
		at org.apache.felix.scr.impl.logger.LogServiceEnabledLogger.getLogger(LogServiceEnabledLogger.java:106) ~[?:?]
		at org.apache.felix.scr.impl.logger.AbstractLogger.isLogEnabled(AbstractLogger.java:71) ~[?:?]
		at org.apache.felix.scr.impl.logger.AbstractLogger.log(AbstractLogger.java:90) ~[?:?]
		at org.apache.felix.scr.impl.Activator.restart(Activator.java:137) ~[?:?]
		at org.apache.felix.scr.impl.config.ScrConfigurationImpl.configure(ScrConfigurationImpl.java:217) ~[?:?]
		at org.apache.felix.scr.impl.config.ScrConfigurationImpl.start(ScrConfigurationImpl.java:120) ~[?:?]
		at org.apache.felix.scr.impl.Activator.start(Activator.java:100) ~[?:?]
		at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:815) ~[?:?]
		at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) ~[?:?]
		at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
		at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:808) ~[?:?]
		... 16 more
```

Maybe you or @maggu2810 know how to solve that or can find an issue with the changes on my branch?

**Comment by maggu2810** [comment]
> Because of [KARAF-6274](https://issues.apache.org/jira/browse/KARAF-6274) we can't update the karaf-maven-plugin to 4.2.5.

What about JBO's comment:
https://issues.apache.org/jira/browse/KARAF-6274?focusedCommentId=16833871&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16833871

**Comment by maggu2810** [comment]
@wborn Can you try to install `openhab-core-base` instead of `openhab-runtime` feature on startup?

https://github.com/wborn/openhab-distro/blob/karaf-4.2.5/distributions/openhab/pom.xml#L134

**Comment by maggu2810** [comment]
* Build openhab distribution.
* Unpack the tgz.
* edit `userdata/etc/org.apache.karaf.features.cfg` and remove the openhab features from `featuresBoot`
* start the distribution `./start.sh`

As soon as you install `openhab-core-base` you will get this message:

```
openhab> feature:install openhab-core-base
org.apache.karaf.features.internal.util.MultiException: Error restarting bundles:
        Exception in org.apache.felix.scr.impl.Activator.start() of bundle org.apache.felix.scr.
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1005)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1058)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:994)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: org.osgi.framework.BundleException: Exception in org.apache.felix.scr.impl.Activator.start() of bundle org.apache.felix.scr.
                at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:836)
                at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:765)
                at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
                at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
                at org.eclipse.osgi.container.Module.doStart(Module.java:589)
                at org.eclipse.osgi.container.Module.start(Module.java:457)
                at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:431)
                at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:450)
                at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:161)
                at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1149)
                at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:997)
                ... 6 more
        Caused by: java.lang.AbstractMethodError: org.ops4j.pax.logging.log4j2.internal.PaxLoggingServiceImpl$1ManagedPaxLoggingService.getLogger(Ljava/lang/String;Ljava/lang/Class;)Lorg/osgi/service/log/Logger;
                at org.apache.felix.scr.impl.logger.R7LogServiceLogger.<init>(R7LogServiceLogger.java:35)
                at org.apache.felix.scr.impl.logger.LogServiceSupport.getLogger(LogServiceSupport.java:69)
                at org.apache.felix.scr.impl.logger.LogServiceEnabledLogger.getLogger(LogServiceEnabledLogger.java:106)
                at org.apache.felix.scr.impl.logger.AbstractLogger.isLogEnabled(AbstractLogger.java:71)
                at org.apache.felix.scr.impl.logger.AbstractLogger.log(AbstractLogger.java:90)
                at org.apache.felix.scr.impl.Activator.restart(Activator.java:137)
                at org.apache.felix.scr.impl.config.ScrConfigurationImpl.configure(ScrConfigurationImpl.java:217)
                at org.apache.felix.scr.impl.config.ScrConfigurationImpl.start(ScrConfigurationImpl.java:120)
                at org.apache.felix.scr.impl.Activator.start(Activator.java:100)
                at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:815)
                at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
                at java.security.AccessController.doPrivileged(Native Method)
                at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:808)
                ... 16 more
Error executing command: Error restarting bundles:
        Exception in org.apache.felix.scr.impl.Activator.start() of bundle org.apache.felix.scr.
```

Same again (start with a clean one) and install `scr` instead of `openhab-core-base`

This will result into the same error.

I am using custom distributions based on karaf 4.2.5 and installing scr and openhab features works as expected.
So I assume this is specific to some openHAB adjustments.

**Comment by maggu2810** [comment]
If I do not change from `felix` to `equinox` as the used OSGi framework, the error does not occur.

```
sed 's:^.*karaf\.framework.*$::g' -i userdata/etc/custom.properties
```

If you would like to use "Equinox" you should ensure that the problem is reported upstream.

**Comment by maggu2810** [comment]
https://lists.apache.org/thread.html/66a37a7bc19540f2656a8fa50cca31d0987b4bfe3dc3200c32a6dfe3@%3Cdev.karaf.apache.org%3E

**Comment by wborn** [comment]
Thanks for reporting it! What are the reasons for using equinox instead of felix with openHAB? Is that so it's more similar to using everything from Eclipse or do we require certain equinox features... or is it because of licensing? :-)

**Comment by maggu2810** [comment]
Hm, this is a very old topic.
I am not sure if I remember correctly.
Perhaps @kaikreuzer should comment.

AFAIK as I started with "bringing openHAB to Karaf" I tried to use the same bundles as has been used in the Eclipse launch configuration.
The event admin of Equinox instead of Apache has been used, we used Equinox DS instead of Felix SCR, ...
We moved step by step and more and more to upstream features and support but the change form Equinox back to Felix has never be done.
Some bundles that are necessary because of Xtext logs some warnings if not used with the Equinox implementation (but they work correcty) and that logs are not created by the "normal" logging framework so they cannot suppressed.

I don't know why openHAB Distro never moved to Felix. Perhaps because all has been working on Equinox and they don't want to change a running system?

I'm curious to see how Kai remembers it.

**Comment by wborn** [comment]
I'd forgotten OH1 didn't use any Karaf at all. So for historic reasons is also a good reason of course. ;-)

So it seems the scr installation exception on Equinox is the same as [KARAF-6259](https://issues.apache.org/jira/browse/KARAF-6259) which will be fixed in 4.2.6.

**Comment by wborn** [comment]
Since there will [soon be a Karaf 4.2.6 release](http://karaf.922171.n3.nabble.com/HEADS-UP-Preparing-Karaf-4-2-6-and-4-3-0-RC1-td4055959.html) (fixing both issues) I made a local build of Karaf 4.2.6 and used if for building the distro ([openhab-2.5.0-SNAPSHOT.tar.gz](https://github.com/wborn/openhab-distro/releases/download/2.5.0-k426.20190523/openhab-2.5.0-SNAPSHOT.tar.gz)) (see also my [karaf-4.2.6 branch](https://github.com/wborn/openhab-distro/tree/karaf-4.2.6)).

The only new issue I ran into is that Jetty is upgraded to 9.4.18.v20190429 and now logs a lot of warnings about weak cipher suites:

```
22:24:00.463 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA256 enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.466 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.467 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.467 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.468 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.468 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.469 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.469 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA256 enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.469 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.470 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.470 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.470 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.471 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.471 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.471 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_GCM_SHA384 enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]
22:24:00.472 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_GCM_SHA256 enabled for SslContextFactory@1301df20[provider=null,keyStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore,trustStore=file:///home/wouter/software/openhab/instance/userdata/etc/keystore]

...

22:25:04.336 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA256 enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.338 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.339 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.340 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.340 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.340 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.341 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.347 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_DHE_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.351 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_DHE_DSS_WITH_AES_256_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.352 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA256 enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.352 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.354 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.355 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.356 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.359 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.359 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.360 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_DHE_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.361 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_DHE_DSS_WITH_AES_128_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.361 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_GCM_SHA384 enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.362 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_GCM_SHA256 enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.379 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA256 enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.379 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.380 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.380 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.381 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.381 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.382 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.383 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_DHE_RSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.384 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_DHE_DSS_WITH_AES_256_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.384 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA256 enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.385 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.386 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.386 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.387 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.388 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.389 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDH_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.389 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_DHE_RSA_WITH_AES_128_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.390 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_DHE_DSS_WITH_AES_128_CBC_SHA enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.391 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_GCM_SHA384 enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
22:25:04.391 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_128_GCM_SHA256 enabled for SslContextFactory@39765aa[provider=null,keyStore=null,trustStore=null]
```

These warnings can be fixed by excluding these weak cipher suites from [jetty.xml](https://github.com/openhab/openhab-distro/blob/69903e9ff7f1d60a93fda6a648271a39c5607713/distributions/openhab/src/main/resources/runtime/etc/jetty.xml#L108) and the [WebClientFactoryImpl class](https://github.com/openhab/openhab-core/blob/d35665c201b10d8391b1717f6663c7cdcd68ec29/bundles/org.openhab.core.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImpl.java#L389-L390) by adding excludes similar to https://github.com/eclipse/jetty.project/pull/2855/files (see also https://github.com/eclipse/jetty.project/issues/2807).

Using the stronger cipher suites may result in worse performance on resource constrained hardware  and it may also cause incompatibility issues. Do you think we should exclude these weaker cipher suites to fix these warnings?

**Comment by wborn** [comment]
Karaf 4.2.6 is [up for vote now](http://karaf.922171.n3.nabble.com/VOTE-Apache-Karaf-runtime-4-2-6-release-td4056133.html) so it's probably gonna be released soon. So without any resolution the Jetty warnings in my previous comment will show when we upgrade. Do you think we should suppress these or exclude the cipher suites @kaikreuzer, @maggu2810?

**Comment by kaikreuzer** [comment]
> I don't know why openHAB Distro never moved to Felix. Perhaps because all has been working on Equinox and they don't want to change a running system?

> I'm curious to see how Kai remembers it.

Yes, that's exactly the reason. openHAB used Equinox from the start in 2010 and there wasn't any reason why it should have been changed, since Karaf has the option to use Equinox as well. And many used frameworks such as EMF and Xtext are usually always used together with Equinox, so the risk of running into bugs is smaller. Changing the framework thus seems to be a risk of introducing instabilities without much benefit.

> Do you think we should suppress these or exclude the cipher suites

I would vote for excluding the cipher suites. After all, people use TLS for security and weak ciphers isn't sensible. If they don't care about security, they can still use plain HTTP for best performance.

**Comment by J-N-K** [comment]
I would vote for excluding the ciphers, for the same reasons as Kai.

**Comment by wborn** [comment]
Thanks for the input! I've created a couple of PRs for this:

* https://github.com/openhab/openhab-core/pull/858

Draft:
* https://github.com/openhab/openhab-distro/pull/924
* https://github.com/openhab/openhab-core/pull/859
* https://github.com/openhab/openhab2-addons/pull/5708
* https://github.com/openhab/openhab-webui/pull/79

The draft PRs are finished but are waiting for Karaf 4.2.6 to be officially released.

**Comment by wborn** [comment]
Karaf 4.2.6 is available on [Maven Central](https://search.maven.org/search?q=org.apache.karaf) so I've removed the Draf status from my PRs!
Maybe you can review/merge them all @kaikreuzer?
You're the only maintainer who can do that on all those repos.

**Comment by kaikreuzer** [comment]
It's my pleasure, @wborn. Many thanks for preparing all the PRs! 🌷

**Pull request merged**
