### PR TITLE
bump JLine using overrides

### PR DESCRIPTION
**Pull request by maggu2810**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Works nicely - thanks!

**Comment by maggu2810** [comment]
It seems we have been to optimistic:
https://github.com/openhab/openhab-distro/commit/6c1614fddf22b66d0674b02969405dff3189c182#commitcomment-25797113

**Comment by kaikreuzer** [comment]
Shall we revert this commit then?

**Comment by maggu2810** [comment]
Yes, we should. :(

**Pull request merged**
