### PR TITLE
Remove Equinox bundle duplicates from runtime launch configuration

### LINKED ISSUE #884: launch config: Equinox bundle duplicates
I have installed openHAB Addons development (only) on the Eclipse IDE 2019-03.

The "openHAB_Runtime" launch configuration contains some Equinox bundles selected in two versions:

* org.eclipse.equinox.region
  * 1.4.0.v20170117-1425
  * 1.4.100.v20171221-2204
* org.eclipse.equinox.transform.hook
  * 1.2.0.v20170105-1446
  * 1.2.100.v20171221-2204
* org.eclipse.equinox.util
  * 1.0.500.v20130404-1337
  * 1.1.0.v20180419-0833
* org.eclipse.equinox.weaving.hook
  * 1.2.0.v20160929-1449
  * 1.2.100.v20171221-2204

The validation problem notification will disappear if you select e.g. the most recent version only of the bundles.

### PR DESCRIPTION
**Pull request by wborn**
The configuration had the following selected:

* org.eclipse.equinox.region
  * 1.4.0.v20170117-1425
  * 1.4.100.v20171221-2204
* org.eclipse.equinox.transform.hook
  * 1.2.0.v20170105-1446
  * 1.2.100.v20171221-2204
* org.eclipse.equinox.util
  * 1.0.500.v20130404-1337
  * 1.1.0.v20180419-0833
* org.eclipse.equinox.weaving.hook
  * 1.2.0.v20160929-1449
  * 1.2.100.v20171221-2204

It now only uses the most recent version.

This works for me but it me (Eclipse: 2018-12 (4.10.0)) but maybe it breaks older IDE versions?

Fixes #884

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Isn't this already addressed by https://github.com/openhab/openhab-distro/pull/882?

**Comment by wborn** [comment]
It's still an issue on the current master with that PR merged.

**Comment by kaikreuzer** [comment]
Interestingly not for me.
@maggu2810 Didn't you do the very same?

**Comment by maggu2810** [comment]
@kaikreuzer I did not test again after #882 has been merged, but there is a good change that there are no duplicate Equinox bundles anymore.

**Comment by Gozilla01** [comment]
I tried a new installation with Latest Release (2018-12)
No duplicate Equinox bundles anymore
PaperUI not work

**Comment by kaikreuzer** [comment]
@Gozilla01 Right, UIs are missing, we will have to add https://dl.bintray.com/openhab/p2/openhab-ui/2.5.x/ to the target platform as well.

**Comment by wborn** [comment]
I've triple checked this:

selection_003

**Comment by maggu2810** [comment]
I have done a fresh new installation of openHAB Addons development now and was able to start the launch configuration without any popup and complaints.

**Comment by maggu2810** [comment]
I checked it again:

Provided bundles by the target platform now, after #882 has been merged:

* org.eclipse.equinox.region
  * ~1.4.0.v20170117-1425~
  * 1.4.100.v20171221-2204
* org.eclipse.equinox.transform.hook
  * ~1.2.0.v20170105-1446~
  * 1.2.100.v20171221-2204
* org.eclipse.equinox.util
  * ~1.0.500.v20130404-1337~
  * 1.1.0.v20180419-0833
* org.eclipse.equinox.weaving.hook
  * ~1.2.0.v20160929-1449~
  * 1.2.100.v20171221-2204

So, there is only one version of the bundles available in the target platform.

**Comment by kaikreuzer** [comment]
@wborn Are you sure you have actually "set" the new target platform?

**Comment by maggu2810** [comment]
If you open the "perfom setup task" dialog, you can try to choose the p2 and target platform tasks only and check after that again.

**Comment by wborn** [comment]
After running the setup tasks again the issue was also fixed for me. Thanks!

**Pull request closed without merging**
