### PR TITLE
Add missing bundles to Demo App for Java 11 compatibility

### PR DESCRIPTION
**Pull request by wborn**
The Demo App can be used with both Java 8 and Java 11 when adding the same runrequires as used with itest projects.
The PR also makes the indentation more consistent by using tabs instead of spaces everywhere in app.bndrun.

Related to https://github.com/openhab/openhab-distro/issues/768

### CODE REVIEW

**Comment by maggu2810** [comment]
I do not know if the setting comes from Eclipse IDE itself or from the Bndtools plugin but for me it seems that with the recent version spaces are used.
At least if I edit the bndrun files in the OpenHAB IDE setup and press tab, spaces are inserted.

**Comment by wborn** [comment]
I opted for tabs because when dragging/dropping bundles or hitting the Resolve button in the Bnd editor it replaces spaces with tabs on my machine. I also see spaces being used when hitting tab on a new line without indentation. But when I press enter at the end of a line that already has tabs it will indent using tabs.

**Comment by maggu2810** [comment]
Okay, thanks for clarification.
Perhaps I will open an issue on Bndtools some time, that a consistent indentation would be nice and if it would be possible to pick up a special formatter.

**Comment by cweitkamp** [comment]
Both are working for me.

When running from IDE on Java 11 I saw a similar warning like you fixed in #1001 for Java 9.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/christoph/.m2/repository/org/apache/servicemix/bundles/org.apache.servicemix.bundles.xstream/1.4.7_1/org.apache.servicemix.bundles.xstream-1.4.7_1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by wborn** [comment]
The warnings will be gone when adding some add-opens using:

```
-runvm: \
	--add-opens java.base/java.io=ALL-UNNAMED,\
	--add-opens java.base/java.lang=ALL-UNNAMED,\
	--add-opens java.base/java.lang.reflect=ALL-UNNAMED,\
	--add-opens java.base/java.net=ALL-UNNAMED,\
	--add-opens java.base/java.security=ALL-UNNAMED,\
	--add-opens java.base/java.text=ALL-UNNAMED,\
	--add-opens java.base/java.util=ALL-UNNAMED,\
	--add-opens java.desktop/java.awt.font=ALL-UNNAMED,\
	--add-opens java.naming/javax.naming.spi=ALL-UNNAMED,\
	--add-opens java.rmi/sun.rmi.transport.tcp=ALL-UNNAMED
```

However that doesn't work with Java 8. It would be nice to keep it all in one file instead of creating a second file for Java 9+. I see there's a [if macro instruction](https://bnd.bndtools.org/macros/if.html) that may help. Perhaps it can check the value of `osgi.ee` in some way but I haven't been successful with that so far. Maybe you or @maggu2810 have some ideas regarding this matter?

**Comment by maggu2810** [comment]
Did you see


```
ee
The name of the highest execution environment found in the current JAR
```

https://bnd.bndtools.org/chapters/855-macros-ref.html

**Comment by wborn** [comment]
Yes I tried that but unfortunately it didn't work.

I've also asked this as question in the bndtools-users group:

https://groups.google.com/forum/#!topic/bndtools-users/GQb-50si8cc

**Comment by wborn** [comment]
Apparently the Java version isn't available so the only remaining option is to move the extra VM parameters to a separate file for Java 9+.

**Comment by wborn** [comment]
Can we merge this @openhab/distro-maintainers?

**Comment by wborn** [comment]
Thanks! Now I can spend my time on other things instead of fixing merge conflicts. :-)

**Pull request merged**
