### PR TITLE
[networkupstools] openHAB1 binding moved to legacy

### PR DESCRIPTION
**Pull request by Hilbrand**
Signed-off-by: Hilbrand Bouwkamp <hilbrand@h72.nl>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
We so far have NOT added such infos to the update.lst file (only for actions that were replaced by a binding). If we say that it isn't enough to list new legacy bindings in the release notes, we should make sure that we add all those to the update.lst. I don't have any preference for the one or the other.

**Comment by Hilbrand** [comment]
I have no preferences. I added it here thinking about what happened when mqtt binding moved to legacy. This surprised a lot of people because at once the binding wasn't directly visible anymore. So I thought to add the alert here so people know why it might not be visible. Although I think this change shouldn't come as a surprise, given the engagement with the community. So if you think it's sufficient to have it in the release notes, feel free to close this pr.

**Comment by J-N-K** [comment]
I would prefer to see this for every binding.

**Comment by wborn** [comment]
If Paper UI didn't show any legacy add-ons by default (only after enabling some filter) we could just keep the legacy add-ons enabled by default. That way the impact of moving add-ons to legacy will be minimized and it would only impact KAR file users (who don't install the legacy add-ons KAR).

Until that time adding such documentation may help. But then it should also list all other such changes because users would then expect all such changes to be listed.

**Comment by kaikreuzer** [comment]
> we could just keep the legacy add-ons enabled by default

I wouldn't change this. But we should add a clear general warning to the release notes that people need to turn on legacy support, if they use such bindings - and we can have a list of the "new" legacy bindings next to it.

**Comment by wborn** [comment]
> I wouldn't change this

What are your reasons for not changing this?

There are also milestone/snapshot users who don't closely follow all community threads who may still run into this issue unless it's addressed by something like automatically generated release notes (https://github.com/openhab/openhab-distro/issues/668).

**Comment by kaikreuzer** [comment]
> What are your reasons for not changing this?

Because it will make all of them appear in the Paper UI (as well as the Karaf console feature list), which might lead to confusion for newbies (and makes the list unnecessarily long).
I consider the legacy support rather to be a feature for long-term users that still have it working. Potentially planning to remove legacy support in future versions, we should encourage people to use 2.x versions and not start with 1.x stuff anymore.
I could imagine that we add a note to the release notes that we recommend anybody who is using 1.x bundles (whether legacy or not) to enable legacy support, then we won't have such problems anymore.

**Comment by Hilbrand** [comment]
Maybe we could add a separate section on OH1 bindings 'replaced' by OH2 bindings in the release notes?

**Comment by kaikreuzer** [comment]
Yes, definitely - we can split the "new bindings" section accordingly.

**Comment by wborn** [comment]
After giving it some thought I think we shouldn't spend to much time on this for OH2 (i.e. just add some documentation) because in OH3 Paper UI might be replaced and support for OH1 add-ons may dropped.

**Comment by Hilbrand** [comment]
I agree to not spent to much time on. But since it can come as a surprise to users when a binding 'just disappears' I think it validates it to have a least some extra attention in release notes. With the oh1 label it should not be to hard to track those changes. I'm going to close my pr here as it doesn't seem needed anymore.

**Pull request closed without merging**
