### PR TITLE
added embedded MQTT broker

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by hakan42** [comment]
Jenkins does not like the fact that someone references "samungtv". I believe this typo is fixed in another PR already?

**Comment by kaikreuzer** [comment]
Build is green again already. And it definitely isn't related to this PR.

**Comment by martinvw** [comment]
O o did I break this build even, 😐

**Comment by kaikreuzer** [comment]
What I meant to say by this is: Don't just approve, also merge! 😛

**Comment by martinvw** [comment]
My phone refuses because github is not all happy

**Pull request merged**
