### PR TITLE
Add java version check to setenv.

### PR DESCRIPTION
**Pull request by dvanherbergen**
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by dvanherbergen** [comment]
This PR adds a Java version check for the shell script. I'll create another PR for the bat file tomorrow.
Addresses #87

**Comment by maggu2810** [comment]
You are using egrep, awk and sed now.
On common linux distributions all that commands (set and awk, perhaps not egrep) should be available.
Custom rootfs could miss some commands.
As Chris already runs in trouble, perhaps he could check which commands are (un)available on his system.

**Comment by dvanherbergen** [comment]
It's a copy paste from the karaf script. If it doesn't work, we have bigger issues...

**Comment by kaikreuzer** [comment]
>  from the karaf script. If it doesn't work, we have bigger issues...

Well, we already have big issues through Karaf (and since the vanilla Karaf does not even work on a RaspPi, I doubt that anybody ever tested it on other embedded platforms), so I agree with @maggu2810 that there is a risk that this breaks things, so we should be careful.

**Comment by kaikreuzer** [comment]
@dvanherbergen Is this check not done in Karaf for Windows?

**Comment by dvanherbergen** [comment]
I did not see it in the karaf.bat.

**Comment by maggu2810** [comment]
For Oracle 1.7, 1.8 Java this one would work on the very most Linux systems:
<code>java -version 2>&1 | head -1 | cut -d\" -f2</code>

Kai, could you test this on MAC?

We could then using a "case ... in 1.8*) ..." (similar to the arch one).

**Comment by kaikreuzer** [comment]
Works on Mac as well.

**Comment by maggu2810** [comment]
Why still using egrep, awk, ...? If we could rely on head and cut only? Do you think there are differences on OpenJDK?

**Pull request merged**
