### PR TITLE
Update openhab.target to openhab-deps-repo

### PR DESCRIPTION
**Pull request by dvanherbergen**
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by dvanherbergen** [comment]
I did some initial testing on this and it seems to work OK, but it would be great if someone could test this more.

**Comment by maggu2810** [comment]
I checked out this PR, started IDE, ensure the new target platform is set and did a clean and rebuild all.
Seems to be working.

**Comment by kaikreuzer** [comment]
openhab-core seems to be working in the target platform. This means that you cannot start the runtime within the IDE anymore!

**Comment by dvanherbergen** [comment]
Not sure how I missed that. My IDE runtime seemed to work OK. Anyway, I've added the openhab-core again.

**Comment by kaikreuzer** [comment]
Looks much better now!
One last question: Why do we still need the luna update site? Can't these dependencies be included in the openhab-deps-repo? Or is this on purpuse, because it only adds the Equinox framework for launch from the IDE and the Maven compilation obviously does not require it?

**Comment by dvanherbergen** [comment]
> the Maven compilation obviously does not require it

Indeed, I started from the builds and tried to keep the dependencies as small as possible to get the best performance in the dependency resolution. 

Currently the openhab-deps-repo already includes two features: one for the compile dependencies and one for tests. We could add a third feature for the IDE runtime. I'm not sure if it will add much value other than keeping the target file a little cleaner.

**Comment by kaikreuzer** [comment]
Ok, makes sense then. Thanks!

**Pull request merged**
