### PR TITLE
Added breaking change for icalendar thing-split

### PR DESCRIPTION
**Pull request by daMihe**
This PR depends on https://github.com/openhab/openhab-addons/pull/14766.

It adds a message for the breaking change resulting from splitting the bridge into smaller things.

### CODE REVIEW

**Review by wborn — CHANGES_REQUESTED** [review]
It should be moved to the right OH version when it gets merged.

**Comment by daMihe** [comment]
Done. Added 4.1.0 section which may collide. If required i'll update again. I'm waiting for a review in the referenced PR.

**Review by wborn — CHANGES_REQUESTED** [review]
As there is a 4.1.0 release now, it again should be moved to the right OH version when it gets merged.

**Comment by daMihe** [comment]
Okay, i'll do when the code gets merged.

**Comment by wborn** [comment]
Let's close this as https://github.com/openhab/openhab-addons/pull/14766 was also closed.

**Pull request closed without merging**
