### PR TITLE
Bump karaf to version 4.0.4

### LINKED ISSUE #18: Karaf 4.0.8 should be tested
``` text
Jean-Baptiste Onofré, 08:48
...
Today I'm fixing the latest Jira for 4.0.4, I should be able to submit 4.0.4 release to vote tomorrow
```

We should test K404 as soon as its voting round starts and we should vote +1 (if all is fine) or -1 (is something is broked) for the release.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29605031-karaf-4-0-7-should-be-tested?utm_campaign=plugin&utm_content=tracker%2F28452711&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F28452711&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by dvanherbergen**
Resolves #18.

Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by dvanherbergen** [comment]
I only did a quick test of the offline distro, but the dashboard and basic ui seem to be working fine. I didn't check for any other issues that 4.0.4 could cause.

**Comment by kaikreuzer** [comment]
I have some odd behavior of the shell. First of all it starts twice with the "openHAB" welcome screen.
And then it is really sluggish when I type commands and even if I manage to type them in, they are not getting in time to the interpreter:
```
openhab> logout
Command not found: lgou
openhab> feature:list
Command not found: otfurlst
openhab> 
```
Do you have the same?

**Comment by dvanherbergen** [comment]
I didn't notice the duplicate logo before.. but yes, I get the same behaviour. I'm wondering if something started twice..

**Comment by dvanherbergen** [comment]
It looks like something is started twice. After changing my config from demo to standard and restarting, it only showed one logo for a second while it was reconfiguring. Then the second logo appeared.

**Comment by dvanherbergen** [comment]
The problem with the console seems like a regression issue: https://community.openhab.org/t/osgi-console-not-using-all-text-input/5282

**Comment by kaikreuzer** [comment]
Hm, interesting, the thread above is from pre-karaf, so it might be some general issue with the gogo shell.

**Comment by kaikreuzer** [comment]
@dvanherbergen Any idea about how to fix the "double-intro" bug?

**Comment by dvanherbergen** [comment]
When openHAB starts, you can see that it launches the console twice, there are 2 threads 'Karaf shell pipe' and 2 threads 'Karaf local console user openhab'.
If you then connect using the karaf/bin/client, then a third one for each is added. The client console itself works as expected. So for some reason it is starting these threads twice on regular startup. No idea why it would do this though...

**Comment by kaikreuzer** [comment]
If there are 2 shells simultaneously, it also explains why the keyboard entries are not correctly processed. I hope you find out what is wrong there!

**Comment by maggu2810** [comment]
K405 is on vote and contains e.g. this bugfix: https://issues.apache.org/jira/browse/KARAF-4072

So we should try to use K405 (perhaps) and not bump to K404 anymore.

Perhaps we need to use K404 for the plugin and K405 for the distribution, but let's wait for the final decision (see: http://karaf.922171.n3.nabble.com/VOTE-Apache-Karaf-4-0-5-release-tp4046085p4046126.html).

**Comment by kaikreuzer** [comment]
Superseded by https://github.com/openhab/openhab-distro/pull/172

**Pull request closed without merging**
