### PR TITLE
Reenable ZigBee binding

### PR DESCRIPTION
**Pull request by wborn**
Also updates the versions and adds the new serial and console bundles.

CC: @cdjackson

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks @wborn, however, can we instead start using the feature generated by the binding itself? I added this a few months back with a view that we can avoid having this feature file here - all dependencies would then be controlled in one place :)

**Comment by wborn** [comment]
I had a look at that and with a few changes it seems to work in general. However currently the generated feature name prevents it from showing up in the UI. The feature name should be `openhab-binding-zigbee` while it currently seems to be derived from the artifactId `org.openhab.addons.features.karaf.zigbee` .

**Comment by wborn** [comment]
OK all is green now. Now we need to find one of the @openhab/distro-maintainers who wants to push the merge button.

**Review by kaikreuzer — APPROVED** [review]
Thanks!
So shall we also move the ZWave feature to its repo as a next step, @cdjackson?

**Pull request merged**
