### PR TITLE
[build fix] karaf 4.0.4-snapshot no longer available. 

### PR DESCRIPTION
**Pull request by dvanherbergen**
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
Have you bumped the dep.karaf.version?
You know that we are using > 4.0.3 because 4.0.3 will not work for some snapshots?

**Comment by dvanherbergen** [comment]
> Have you bumped the dep.karaf.version?

No. That is still on 4.0.3. The only one using 4.0.4-snapshot was the openhab-aggregate-kar.
Before we can move everything to 4.0.4, https://github.com/openhab/openhab-distro/issues/18#issuecomment-172134178 needs to be fixed.

> Have you considered that we are using > 4.0.3 because 4.0.3 will not work for some snapshots?

I've tested the distro build with this change to 4.0.3 and that works OK. Which snapshot are you referring too?

**Comment by maggu2810** [comment]
The KAR creation for snapshots artifacts could be broken in <= 4.0.3. That is the reason why we have used > 4.0.3 (4.0.4-SNAPSHOT) for the KAR creation only.
https://github.com/apache/karaf/pull/102

**Comment by dvanherbergen** [comment]
OK, so should we bump the version for the KAR creation or try to bump everything?

**Comment by maggu2810** [comment]
We could bump the KAR creation to 4.0.4 as a fix (keep a TODO that we should remove the explicit version as soon as >= 4.0.4 is used for the whole repo).

The bump of the whole distribution could be more work and should be done in a separate PR. As I mentioned earlier, all the changed configurations need to be checked. If the unchanged / upstream configuration file contains more / less stuff now, we have to "merge" that change to our modified one, too.

I asked JBO to include the mechanism to edit configuration files by the build process some time ago and it was able to include that mechanism in K404.
See: https://github.com/apache/karaf/pull/80
Using this feature we could perhaps drop some hard coded files.

**Pull request merged**
