### PR TITLE
[setup] Renamed master to main for addons setup

### PR DESCRIPTION
**Pull request by Hilbrand**
And rename of addons master to main.

### CODE REVIEW

**Comment by mhilbush** [comment]
Thanks!!

**Comment by hmerk** [comment]
@Hilbrand What about someone wants to enhance a 2.5.x binding or fix bugs ? 2.5.x development would still be needed then, am I wright ?

**Comment by kaikreuzer** [comment]
I'd agree with @hmerk - I would leave the option to set up an IDE for 2.5 as well.

**Comment by kaikreuzer** [comment]
@Hilbrand Would you agree to keep the 2.5.x parts?

**Comment by Hilbrand** [comment]
Yes i had not time to update. I was looking at changing the default to java 11, which should work for 2.5.x. I have some local changes and am working on updating  the documentation.

**Comment by Hilbrand** [comment]
Removed the removal of 2.5.x I'll look into the default to  java 11 in the setup later. Because I need to check this won't break 2.5.x development because that should still work with java 8.

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
