### PR TITLE
Revert "enable authentication by default"

### PR DESCRIPTION
**Pull request by kaikreuzer**
Reverts openhab/openhab-distro#782

### CODE REVIEW

**Comment by mstormi** [comment]
That revert didn't (fully?) revert, snapshot #1386 is still asking for auth ...

**Comment by kaikreuzer** [comment]
@splatch What is missing?

**Comment by mstormi** [comment]
FWIW, using #1383 now, that still does not work. Not asking for auth but it's redirecting the Basic UI URL to some .../login?.... which then is a 404.
So not sure how far back you need to go.

**Comment by kaikreuzer** [comment]
@splatch Latest build is completely broken as it asks for auth, but does not accept the jaas user (openhab/habopen). What does one have to do to disable it? Or is the only chance to also revert the openhab-core PR, which added the bundles?

**Comment by kaikreuzer** [comment]
@splatch I was talking about what is missing fir DEACTIVATING the feature for now. Does this require to fully remove the bundles again, i.e. also revert the openhab-core PR?

**Comment by splatch** [comment]
I'm on it.

**Pull request merged**
