### PR TITLE
Restructured folder layout

### PR DESCRIPTION
**Pull request by kaikreuzer**
- moved runtime/karaf/etc folder to userdata/etc
- removed runtime/etc, only kept runtime/services.cfg (moved from runtime/etc/services.cfg)
- moved runtime/karaf to runtime
- moved userdata/lock to userdata/tmp/lock
- removed userdata/deploy
- removed userdata/kar

Fixes https://github.com/openhab/openhab-distro/issues/315
Fixes https://github.com/openhab/openhab-distro/issues/225

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This PR introduces some changes in the directory structure that might have impact on other parts.

@theoweiss Could you please check if anything needs to be adapted for the debian packaging? Please note that with that change the start.sh script in the root is adapted, so this needs to be taken into account.

@ThomDietrich Can you assess the implications on the documentation? I didn't see too much that would need to be adapted.

@cniweb Please check that Docker and Synology images correctly handle this change.

**Comment by theoweiss** [comment]
@kaikreuzer I'll check it.

**Comment by cniweb** [comment]
Hi Kai,

we must modify:
https://github.com/openhab/openhab-syno-spk/blob/2.0-SNAPSHOT-DSM6/scripts/start-stop-status.sh#L52
and (@cyberkov)
https://github.com/openhab/openhab-docker/blob/master/files/entrypoint.sh#L24
and (@thopiekar)
https://github.com/openhab/openhab-qnap-qpkg/blob/master/shared/openHAB.sh#L14

Chris

**Comment by thopiekar** [comment]
Thank you @cniweb for the mention and keeping me up to date..

Are there other changes except of the runtime/karaf/bin path which has changed?
Are our directories, which we are purging after an update, still save to remove?
See: https://github.com/openhab/openhab-qnap-qpkg/blob/master/shared/openHAB.sh#L141

Regards and thank you for your work on that, @kaikreuzer 👍

**Comment by ThomDietrich** [comment]
Regarding docs:
* https://github.com/openhab/openhab-docs/blob/gh-pages/administration/console.md#configuring-the-console

* This section should probably be updated anyways: https://github.com/openhab/openhab-docs/blob/gh-pages/administration/logging.md#config-file

* @cniweb I'm sure you are aware of https://github.com/openhab/openhab-docs/blob/gh-pages/installation/docker.md

The first two are quick changes I can do after this PR is merged.

One easy change is also needed in openHABian: https://github.com/ThomDietrich/openhabian/issues/34

**Comment by cniweb** [comment]
@ThomDietrich, yes, we must modify:
https://github.com/openhab/openhab-docs/blame/gh-pages/installation/docker.md#L59

**Comment by kaikreuzer** [comment]
> Thank you @cniweb for the mention and keeping me up to date..

Sorry @thopiekar for having missed you - I somehow didn't remember that your QNAP package also does OH2 :-) Will keep you in the loop in future as well :-)

All, thanks for your prompt feedback! So in general, I take your responses as an approval of this change.

For the planning, I would suggest to merge this on Thursday, if nobody vetoes.

**Comment by thopiekar** [comment]
@kaikreuzer You are not alone here after all and at the end I was mentioned here, too. So at the end no problem at all.

Just one question left: Do we have to care about keeping the current settings save on updates/upgrades? Eg. moving the settings from the old to the new locations?

**Comment by kaikreuzer** [comment]
@thopiekar As so far the settings always got lost with every update, I don't think we have to take care of that - not sure though, how you have handled the upgrade procedure so far? Did you keep runtime/karaf/etc folder in place?

**Comment by thopiekar** [comment]
@kaikreuzer So far I followed the instructions by a user from the forums and just replaced the runtime and removed the userdata/cache and userdata/tmp, as you can see here: https://github.com/openhab/openhab-qnap-qpkg/blob/master/shared/openHAB.sh#L141

Until now I didn't know that I also had to care about runtime/karaf/etc :roll_eyes:

**Comment by kaikreuzer** [comment]
> Until now I didn't know that I also had to care about runtime/karaf/etc 

Nobody knew and soon nobody has to know :-)

But good, your procedure is then very much in line with what I suggest in https://github.com/openhab/openhab-distro/issues/299.

**Comment by thopiekar** [comment]
#299 sounds good. Hope we'll find more problems there.
I already had strange effects e.g. when using the Zwave binding, where reinstalling was the only and last solution. However, maybe they will be fixed with this PR :dancer:

**Comment by kgoderis** [comment]
I think we should also move org.apache.karaf.shell.cfg, specifically for the sshPort and sshHost parameters that are typically modified by users

Moreover, as a Mac OS user, I also have to save and restore any openhab-wrapper*.* related files in order to keep things running. That is not only runtime/karaf/etc/openHAB-wrapper.conf and siblings, but also runtime/karaf/lib/wrapper/*

**Comment by kaikreuzer** [comment]
@kgoderis See the very first line in this issue. The whole etc folder is moved. 
Regarding the wrapper: This anyhow is currently broken (at least according to my tests). Feel free to come up with changes to https://github.com/openhab/openhab-core/blob/8a7f5561b1652d1c080d2a7fdc823c8d4bf93b31/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/command/InstallServiceCommand.java to make sure that nothing relevant is written in the runtime folder.

**Comment by thopiekar** [comment]
@kaikreuzer I'm preparing a PR at the moment for QPKG.
Is there a need to keep runtime/services.cfg during update? My current procedure would remove this file.

**Comment by ThomDietrich** [comment]
Without being able to give a clear answer on the question, here's a more general idea:
I would expect a file named `runtime/services.cfg` to be of some importance and to contain settings a user should not delete... If this is not the case the file might be named incorrectly... jm2c...

**Comment by kaikreuzer** [comment]
`runtime/services.cfg` contains the basis configuration settings of the runtime, it must not be changed by the user - therefore it does not have to be kept on a system update (the new runtime actually expects to find the current version of the file). That's why it is in the runtime folder, which is meant to be fully replaced as mentioned [here](https://github.com/openhab/openhab-distro/issues/299#issue-183202613).

**Comment by thopiekar** [comment]
Looks like we are well prepared now. Hope my migration method won't break anything 🙈

**Comment by theoweiss** [comment]
Unfortunately  I can't look at this before the weekend :-(

**Comment by thopiekar** [comment]
@theoweiss Could you lead me to your packaging files? Is/was packaging OH2 complicated for Debian? Maybe I could jump in and make a PR :)

(About myself: I already package/packaged several other projects on launchpad :wink: )

**Comment by theoweiss** [comment]
Thanks @thopiekar,

the deb packaging uses maven with jdeb and is embedded in the maven build of the openhab-distro project. The jdeb configuration starts here
 https://github.com/openhab/openhab-distro/blob/master/distributions/pom.xml#L32
Debian control files and other resources are here: 
https://github.com/openhab/openhab-distro/tree/master/distributions/distribution-resources/src/main/resources/deb
You will find the jdeb documentation here:
https://github.com/tcurdt/jdeb/blob/master/docs/maven.md

**Comment by thopiekar** [comment]
Ok, this really seems to be a bit more of work. Never used jdeb before.
What will likely happen if we don't update these instructions? Will the whole build of the distro fail?
And how can I test my changes? A the moment I wouldn't try more than updating the paths...

**Comment by theoweiss** [comment]
* clone the openhab-distro project
 * make your changes 
 * execute `mvn clean install` in the top level directory of the project
 * you will find a dpkg installable deb package distributions/openhab-offline/target/openhab2-offline-2.0.0-SNAPSHOT.deb and distributions/openhab-online/target/openhab2-online-2.0.0-SNAPSHOT.deb
 * if you want to install the package with apt the build also generates to apt repositories:
   * distributions/openhab-offline/target/apt-repo/
   * distributions/openhab-online/target/apt-repo/
   * for serving these repos cd into one of these directories and start a web server, e.g.
```
cd distributions/openhab-offline/target/apt-repo/
# start a python web server which serves the current directory
python -m SimpleHTTPServer 8082
```
  * to use this repo for installation login to your test system and add a line like this to your apt sources
```
deb http://<ip_of_your_build_host>:8082/ / 
# e.g http://192.168.178.29 :8082/ / 
```
  * then `apt-get update && apt-get install openhab2-offline` (or openhab2-online) should do the trick

**Comment by thopiekar** [comment]
Ok, having the deb at the end should be enough.. a simple `sudo dpkg -i <deb-file>` should be enough, too :smile:

**Comment by kaikreuzer** [comment]
Does this mean we are ok to merge this PR right now?

**Comment by thopiekar** [comment]
@kaikreuzer: @theoweiss didn't answer my question whether it would break all the other builds if we don't correct the jdeb build. So I guess there is no impact and we can merge this(?).

**Comment by kaikreuzer** [comment]
Let's wait for a moment and give @theoweiss a chance to clearly articulate a veto, if necessary ;-)

**Comment by thopiekar** [comment]
@kaikreuzer checking out your branch and trying to `mvn clean install` fails here:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] openHAB Distribution ............................... SUCCESS [  0.280 s]
[INFO] openHAB Features ................................... SUCCESS [  0.012 s]
[INFO] openHAB Demo Feature Resources ..................... SUCCESS [  0.784 s]
[INFO] openHAB Demo Feature ............................... SUCCESS [  2.321 s]
[INFO] openHAB Feature Aggregate XML ...................... SUCCESS [ 13.344 s]
[INFO] openHAB Feature Aggregate KAR ...................... SUCCESS [01:51 min]
[INFO] openHAB Experimental Feature Addons ................ SUCCESS [  0.589 s]
[INFO] openHAB Feature Verification ....................... FAILURE [  0.827 s]
[INFO] openHAB Distributions .............................. SKIPPED
[INFO] openHAB Offline Distribution ....................... SKIPPED
[INFO] openHAB Online Distribution ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:11 min
[INFO] Finished at: 2016-11-10T11:08:27+01:00
[INFO] Final Memory: 23M/455M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.0.4:verify (verify) on project openhab-verify: Unable to load features descriptors: Error -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openhab-verify
```

whereas the unchanged current openhab/openhab-distro works.

**Comment by theoweiss** [comment]
The build may work but at least the apt-repo for the snapshots would possibly deliver broken packages.

**Comment by kaikreuzer** [comment]
According to https://github.com/openhab/openhab-distro/issues/321, the deb packages are anyhow broken right now, so we won't be able to break much by merging...?

**Comment by kaikreuzer** [comment]
> @kaikreuzer checking out your branch and trying to mvn clean install fails here:

@thopiekar I'll test it again.

**Comment by kaikreuzer** [comment]
@thopiekar:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] openHAB Distribution ............................... SUCCESS [  0.204 s]
[INFO] openHAB Features ................................... SUCCESS [  0.021 s]
[INFO] openHAB Demo Feature Resources ..................... SUCCESS [  0.256 s]
[INFO] openHAB Demo Feature ............................... SUCCESS [  1.536 s]
[INFO] openHAB Feature Aggregate XML ...................... SUCCESS [ 15.229 s]
[INFO] openHAB Feature Aggregate KAR ...................... SUCCESS [04:41 min]
[INFO] openHAB Experimental Feature Addons ................ SUCCESS [  0.392 s]
[INFO] openHAB Feature Verification ....................... SUCCESS [04:24 min]
[INFO] openHAB Distributions .............................. SUCCESS [  0.005 s]
[INFO] openHAB Offline Distribution ....................... SUCCESS [ 58.955 s]
[INFO] openHAB Online Distribution ........................ SUCCESS [ 37.689 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:02 min
[INFO] Finished at: 2016-11-10T13:52:42+01:00
[INFO] Final Memory: 29M/1007M
[INFO] ------------------------------------------------------------------------
```

**Comment by kaikreuzer** [comment]
Let's see what Cloudbees says :-)

**Comment by cniweb** [comment]
Cloudbees says: LGTM:
https://openhab.ci.cloudbees.com/job/openHAB-Distribution/579/

**Comment by BClark09** [comment]
uh oh... 

```
start.sh[16630]: karaf: KARAF_BASE is not valid: /usr/share/openhab2/userdata
systemd[1]: openhab2.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by ThomDietrich** [comment]
Well we could have expected that -.- How about this as a quick and dirty solution:
```
apt remove openhab-offline
mv /usr/share/openhab2/runtime/karaf/etc/* /var/lib/openhab2/etc/
rm -r /usr/share/openhab2
rm -r /var/lib/openhab2/{kar,lock,deploy}
apt install openhab-offline
```

**Comment by mdilger** [comment]
I saw a similar message on the console today after updating on Windows 7.  That said everything seems to work OK.

Only thing I noticed is the file userdata/lock has not moved to userdata/tmp/lock

**Comment by BClark09** [comment]
> Well we could have expected that -.-

I completely forgot about this PR before I updated for different reasons.

> So far I found wrong paths in /usr/share/openhab2/runtime/bin/oh2_dir_layout, /etc/init.d/openhab2, /usr/lib/systemd/system/openhab2.service

Although I purged before doing this, changing the three files above after the install was all that was necessary to have a working openHAB again.

**Comment by ThomDietrich** [comment]
I'm not free right now. Could you hack together the right `sed` lines?

**Comment by BClark09** [comment]
Yes, a bash file that would get Debian openHAB users running again would be:

```
#!/bin/bash

sed -i -e 's|/usr/share/openhab2/runtime/karaf/bin/|/usr/share/openhab2/runtime/bin/|g' /etc/init.d/openhab2 /usr/lib/systemd/system/openhab2.service
sed -i -e 's|OPENHAB_USERDATA="${OPENHAB_HOME}/userdata"|OPENHAB_USERDATA="/var/lib/openhab2"|g' /usr/share/openhab2/runtime/bin/oh2_dir_layout
sed -i -e 's|OPENHAB_CONF="${OPENHAB_HOME}/conf"|OPENHAB_CONF="/etc/openhab2"|g' /usr/share/openhab2/runtime/bin/oh2_dir_layout
sed -i -e 's|OPENHAB_LOGDIR="${OPENHAB_USERDATA}/logs"|OPENHAB_LOGDIR="/var/log/openhab2"|g' /usr/share/openhab2/runtime/bin/oh2_dir_layout

systemctl daemon-reload
service openhab2 start
```

**Comment by ThomDietrich** [comment]
Lgtm. Thanks!
Not sure if the steps mentioned above are additionally meaningful beforehand.
I did not change OPENHAB_CONF nor OPENHAB_LOGDIR. Are you sure that's needed?

**Comment by BClark09** [comment]
The items/sitemaps won't refresh unless the path is set correctly. The logs can stay where they're being set and won't break the package,  but I assumed the apt packages still wanted logs in /var/log like other services instead of /var/lib.

**Comment by ThomDietrich** [comment]
Judging by the comments in the forum I think the `mv` (or as a cp) should have been part of your solution...

**Comment by BClark09** [comment]
I'll edit anywhere I've mentioned it. Meanwhile, I'm working on a PR to fix the issue for the deb package.

**Comment by ThomDietrich** [comment]
Good idea! @theoweiss and @thopiekar might be interested to know.

**Comment by BClark09** [comment]
I believe I've made the appropriate necessary changes at: https://github.com/BClark09/openhab-distro/tree/deb-fix

But I'm currently testing it before I make the PR.

**Comment by ThomDietrich** [comment]
Looks good but I'm missing special upgrade steps. As I see it this will deliberately damage every upgrading users setup!?
I think the right place to put the needed rearrangement of files and folders as per the first posting is here: https://github.com/BClark09/openhab-distro/blob/master/distributions/distribution-resources/src/main/resources/deb/control-runtime/preinst

**Comment by BClark09** [comment]
> this will deliberately damage every upgrading users setup!?

That sounds scary, in what way?

**Comment by ThomDietrich** [comment]
I'm sorry if I'm wrong! e.g. https://community.openhab.org/t/new-folder-structure/16526/13
I believe this happened because the host key file is not carried on

**Comment by BClark09** [comment]
This happens because it's moved, it would have been replaced each time anyway right?

`ssh-keygen -R openhab@localhost` might be a step that's required only when upgrading pre to post this PR. But I wouldn't know how I should check for that?

Since I'm currently running on the build Debian package of my branch, I think I should make a PR and let @theoweiss give the all clear?

**Comment by ThomDietrich** [comment]
Okay I'm not sure either. I think priority is to get a fix for the more eminent problem out there.
Create the PR and either Theo or Kai can decide if it's worth to wait.

**Comment by sihui62** [comment]
> it would have been replaced each time before this PR anyway right?

Just to mention: I'm using the online openHAB2 version (manually installed, no apt) and I had to use the command `ssh-keygen -f "/home/pi/.ssh/known_hosts" -R [localhost]:8101` on EVERY update of openHAB2. So from my experience it has nothing to do with this PR. (but I'm only  a user, not a programmer ...)

**Comment by ThomDietrich** [comment]
The error message says "REMOTE HOST IDENTIFICATION HAS CHANGED" and "It is also possible that a host key has just been changed".
I see this message from time to time when I reinstall a server or a RPi and the key changes. In openHAB the key for the karaf console is `runtime/karaf/etc/host.key` (more or less). So yes the key can simply be deleted from your known_hosts, you could also just carry it with while upgrading ;) There are other files in /runtume/karaf/etc users might have modified and worth to be copied... jmho

**Comment by BClark09** [comment]
Fair enough, I agree, do you think the following would be sufficient?

```
#...
OLD_ETC=/var/lib/openhab2/etc/
NEW_ETC=/usr/share/openhab2/runtime/karaf/etc/
#...
moveOldDir(){
  [ ! -d ${NEW_ETC} ] && mkdir -p ${NEW_ETC}
  [ -d ${OLD_ETC} ] && mv ${OLD_ETC}* ${NEW_ETC} && rm ${OLD_ETC}
  rm -rf /var/lib/openhab2/{kar,lock,deploy}
  true
}
#...
  upgrade)
    moveOldDir
    ;;
#...

**Comment by thopiekar** [comment]
@BClark09 Are you sure that this script works?
I personally see the problem that APT will fail to install as it will find unexpectedly the config files.
In my point of view I would move it into postinstall, just before the postinstall starts the service itself.

See: https://wiki.debian.org/DpkgConffileHandling - section: "Moving a conffile"

Btw. they argue the same:
```
If we moved the conffile in the preinst script, dpkg would unpack the new package and see that the conffile has changed and ask the user what to do about it. We want to avoid that, so we let dpkg unpack the package without conflict. We can now handle moving the user-changed conffile into place in the postinst script. 
```
But I think it depends on which behavior we want here...

**Comment by ThomDietrich** [comment]
I'm no expert here by all means.
I decided to go with preinst *because* I want these files to be handled by the installer. Just as it was before.

**Comment by BClark09** [comment]
I think we should be okay for this instance because we're moving non-conf files to become conf files. The majority of the file contents will not have changed and if they have then of course we should prompt the user.

**Comment by thopiekar** [comment]
Ok, so there are no problems by openhab-distro itself? (Without looking at the problems we have in our different packages..)

**Comment by ThomDietrich** [comment]
Aside the changes to the deb related files my system seems to work again. We will see...
@BClark09 I've corrected my script over in the PR [comment](https://github.com/openhab/openhab-distro/pull/322#issuecomment-260045142). Maybe it's worth to be included after all...

**Comment by ThomDietrich** [comment]
@kaikreuzer docs.openhab.org is up to speed.

**Comment by llamahunter** [comment]
What's the status of fixing the broken paths?

**Comment by ThomDietrich** [comment]
The problem with broken paths is related only to deb based installation. Discussed in a new issue: https://github.com/openhab/openhab-distro/pull/322

**Comment by ThomDietrich** [comment]
@kaikreuzer Same goes for openHABian

**Comment by kgoderis** [comment]
> Regarding the wrapper: This anyhow is currently broken (at least according to my tests). Feel free to come up with changes to https://github.com/openhab/openhab-core/blob/8a7f5561b1652d1c080d2a7fdc823c8d4bf93b31/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/command/InstallServiceCommand.java to make sure that nothing relevant is written in the runtime folder.

Not sure that this is even possible, as the call to wrapperService.install() seems to imply that there is little control as to which folders will be used. I am by no means a Karaf expert, so maybe @dvanherbergen  you can have a look at this? [Secondly, I have no clue how to set up the IDE so that it uses Karaf for debugging purposes]

**Pull request merged**
