### PR TITLE
Bump ZigBee libraries to 1.1.1

### PR DESCRIPTION
**Pull request by cdjackson**
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by najib-halimi** [comment]
hello, 
I am unemployed and promised a job if I could get this  project of locking and unlocking Yale Zigbee lock working. 

Any thing you can do to help (expedite this merge)  is greatly appreciated.

**Comment by martinvw** [comment]
@kaikreuzer it looks fine to me 🙂

**Comment by kaikreuzer** [comment]
We should wait until https://github.com/openhab/openhab-deps-repo/pull/8 is merged and the TP is updated accordingly as well.

**Comment by najib-halimi** [comment]
Any idea of when will " openhab/openhab-deps-repo#8 is merged and the TP is updated accordingly as well." this happen?

**Comment by kaikreuzer** [comment]
I have created https://github.com/openhab/openhab-core/pull/388.

**Comment by cdjackson** [comment]
Thanks Kai.

**Pull request merged**
