### PR TITLE
Fix SSE streams when using GZIP

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes https://github.com/openhab/openhab-webui/issues/1757

It seems that enabling GZIP for the SSE endpoints breaks the ecent stream.

### CODE REVIEW

**Comment by wborn** [comment]
Did you also consider to only include the mime types that are known to work by calling [addIncludedMimeTypes](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/server/handler/gzip/GzipHandler.html#addIncludedMimeTypes(java.lang.String...))? If that works we won't have to manage the list of endpoints.

**Comment by J-N-K** [comment]
That also works.

**Review by wborn — APPROVED** [review]
Thanks! :+1:

**Comment by lolodomo** [comment]
I just tested with this version of jetty.xml and it also works again for me.
Thank you.

**Pull request merged**
