### PR TITLE
Removing files that must not exist anymore in an installation upon upgrade

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@BClark09 & @cniweb What needs to be done on the linux-pkg and docker side to ensure that those two files are removed from the userdata folder?

**Comment by BClark09** [comment]
I've merged a temporary fix for linuxpkg. Will keep it until we nail down the CSV upgrade procedure.

**Comment by kaikreuzer** [comment]
Perfect, thanks!

**Comment by BClark09** [comment]
No worries 😃 , I noticed the linuxpkg build has been disabled. Is there more to do before it is enabled again?

**Comment by kaikreuzer** [comment]
I built the new distro and am testing it currently - I just wanted to avoid to roll it out to apt and docker at the same time. I'll enable it, once my tests look good (probably later tonight).

**Comment by BClark09** [comment]
Awesome, looks good so far!

**Comment by kaikreuzer** [comment]
Running the linux-pkg now and announcing the new distro: https://community.openhab.org/t/unit-support-knx-2-karaf-4-1-5-upgrade-and-more/41904

**Comment by BasvanH** [comment]
@kaikreuzer , do you want me to gather some logs or so?

**Comment by kaikreuzer** [comment]
I don't think there is any need for logs - you might just want to open an issue at https://github.com/openhab/openhab-docker/issues and refer to this issue here - it should then be clear what needs to be done.

**Comment by cniweb** [comment]
What we need to do here?

**Pull request merged**
