### PR TITLE
fixed warnings in demo.rules

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey Kai,
while you are at it, how about a auto-formatter run to get some sane formats?

This can't be the standard we want to set for new users:
```java
if(timer===null) {
if( max !== null && min !== null) {
```

**Comment by martinvw** [comment]
@kaikreuzer shall I take care of this?

**Comment by martinvw** [comment]
@kubawolanin does vscode already support auto-formatting of openHAB config files?

**Comment by kubawolanin** [comment]
@martinvw it does not, but I've posted https://github.com/openhab/openhab-vscode/issues/66 for it ;-)

**Comment by kaikreuzer** [comment]
> Unfortunately I can not push to this branch since (I believe) I'm not an admin in this repo

Imho formatting is unrelated to this PR. So anyone is free to come up with a PR that changes the formatting, but I'd suggest to merge this as it is.

**Comment by martinvw** [comment]
agreed LGTM

**Comment by kaikreuzer** [comment]
Have a try if you can merge then :-)

**Pull request merged**
