### PR TITLE
Fix #519 using Karaf Deployer 4.1.3-sp1 override

### LINKED ISSUE #519: openHAB fails to start if addons.kar is used
Seemingly since the Karaf upgrade from 4.0.8 to 4.1.2, the runtime fails to start if the addons.kar file is used (instead of having it download the addons from the remote repo).

On the first startup everything seems fine, but once the runtime is restarted for the first time, it starts failing. See details about the symptoms in https://github.com/openhab/openhab-distro/issues/518.

### PR DESCRIPTION
**Pull request by wborn**
Fixes #519 through an override. 

This override can be removed when a Karaf version is integrated with a fix for [KARAF-5533](https://issues.apache.org/jira/browse/KARAF-5533).

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I'll deploy the sp1 jar to bintray so that our build can find it.
Nonetheless, you missed to also add the info to the override.properties file and you planned to remove the commented logging configuration.

**Comment by kaikreuzer** [comment]
I have deployed the file to https://bintray.com/openhab/mvn/karaf/4.1.3-sp1, so it should be found by the build.

**Comment by wborn** [comment]
Thanks! Let's retrigger it with close/reopen to see what the result is.

**Comment by kaikreuzer** [comment]
Give me a sec - it is still not turning up on https://openhab.jfrog.io/openhab/libs-release/org/apache/karaf/deployer/org.apache.karaf.deployer.kar/, so I'll have to check if some index needs to be resynced first...

**Comment by kaikreuzer** [comment]
Seems to work now!

**Comment by kaikreuzer** [comment]
(will trigger a new distro build and we can "silently" test it tomorrow - if all looks fine, I'll post the news in the forum as well tomorrow night.)

**Comment by wborn** [comment]
> You cannot believe how glad I am that this is finally solved! Many many thanks for your help (and don't spend the whole bounty on beer :rofl: )!

Yes its nice to have this finally closed :+1:  I also like a good challenge from time to time. Probably I'll reinvest it into other issues! It would be nice if ESH would also allow for bounties. :yum:

**Comment by BClark09** [comment]
Incredible work @wborn!

**Comment by kaikreuzer** [comment]
@wborn While you are at restart issues, would you want to also check the issue when having jars in the addon folder that has been [reported here](https://community.openhab.org/t/jetty-update-karaf-4-1-3-upgrade-and-full-lsp-support/36354/118?u=kai) by quite some users? I'd hope that we can get it solved by fiddling with the [Fileinstall parameters](http://felix.apache.org/documentation/subprojects/apache-felix-file-install.html), e.g. `start.level`, `active.level` and `poll`, wdyt?

> It would be nice if ESH would also allow for bounties.

It actually does! See https://www.bountysource.com/teams/eclipse

**Comment by wborn** [comment]
> check the issue when having jars in the addon folder that has been reported here by quite some users?

Is there an issue/reproduction scenario for this? I have never seen this myself. I always make sure /cache, /kar and /tmp are cleaned when reusing the same instance.

**Comment by kaikreuzer** [comment]
> will trigger a new distro build

Argh, not that easy - for some reason, the build fails now - but it seems unrelated to this PR.

> Is there an issue/reproduction scenario for this?

Nothing more than the reports in the forum so far.

**Pull request merged**
