### PR TITLE
Revert "migrate from EclipseSource JAX-RS publisher to openHAB one (#932)"

### PR DESCRIPTION
**Pull request by kaikreuzer**
This reverts commit a4e5cbd7a4713360bc9a29ab5adca5e93d5b4e37.

See https://github.com/openhab/openhab-core/issues/924#issuecomment-511787620

### CODE REVIEW

**Comment by maggu2810** [comment]
You are missing the Signed-off-by line in the commit message.

**Comment by kaikreuzer** [comment]
I used Gits "reverse commit" feature, which does not add any sign-offs (as they don't make much sense since the commit does not include any copyrightable content from me).

Will check, why this PR is now in conflict...

**Comment by kaikreuzer** [comment]
I used Gits "reverse commit" feature, which does not add any sign-offs (as they don't make much sense since the commit does not include any copyrightable content from me).

Will check, why this PR is now in conflict...

**Comment by kaikreuzer** [comment]
Conflict resolved.

**Comment by maggu2810** [comment]
> I used Gits "reverse commit" feature, which does not add any sign-offs (as they don't make much sense since the commit does not include any copyrightable content from me).

Already answered to the other topic. If you use "-s" on `git revert` it will add the sign off header similar to "-s" on `git commit`.
AFAIK every code contribution regardless if it adds code that has been already part some time of the repo or new one should be signed off.

**Pull request merged**
