### PR TITLE
added task to install compat layer when testing openHAB 1 add-ons

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
You can remove one space between "-" and "A" (<code>+ -  As with</code>).

**Comment by kaikreuzer** [comment]
fixed.

**Comment by lolodomo** [comment]
@kaikreuzer : JUst one little question: why the compat layer is not a bundle installed by default ?

**Comment by kaikreuzer** [comment]
Why should it? If someone does not use any 1.x add-ons there is no need for it.
And once an add-on is added to the distro (see step 6 on https://github.com/openhab/openhab-distro/blob/master/docs/sources/features/compatibilitylayer.md), the compat layer is automatically installed when installing the add-on (so the user does not have to do that).

**Comment by lolodomo** [comment]
If automatic, why mentioning to do it manually ?

**Comment by kaikreuzer** [comment]
Because this is the documentation for developers on "How to use openHAB 1.x Add-ons that are not part of the distribution"

**Comment by maggu2810** [comment]
@lolodomo If you install addons / bundles using features / extension management, the compat layer will be installed if necessary. As this dependencies are defined.
If you install bundles using the addons directory / file deployment, you have to ensure yourself that dependencies will be installed.

**Comment by lolodomo** [comment]
That is clearer with this last explanation.
Thank you.

**Pull request merged**
