### PR TITLE
Remove Java 11 nashorn.args

### PR DESCRIPTION
**Pull request by wborn**
They cause issues when used with Java 8.

Fixes https://github.com/openhab/openhab-addons/issues/7880

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Interesting. How can this setting have such an impact...?

**Comment by wborn** [comment]
Yes I also thought it would be pretty harmless when used with Java 8.
But it seems to panic when it doesn't know what to do with it. :disappointed:

**Comment by helmar74** [comment]
Hi,

how could I solve the issue in my Openhab 2.5.6 environment? (Updated today)

Thanks a lot

**Comment by wborn** [comment]
Remove the line from the `runtime/bin/setenv(.bat)` script as you can see in the [changes](https://github.com/openhab/openhab-distro/pull/1117/files).

**Comment by helmar74** [comment]
ok, do I have to stop OH before and restart after the change?

**Comment by wborn** [comment]
It doesn't really matter because the file is only read at startup. Just make the change and restart openHAB.

**Comment by kaikreuzer** [comment]
Tested latest distro and I can confirm that it solves the issue, thanks!
It'll probably make sense to just do a new 2.5.6 distro binary with that as none of the add-ons have changed.

**Comment by BClark09** [comment]
Hi @kaikreuzer, have you started the new build? I'll make sure to build 2.5.6-2 for the APT and YUM repos and then manually delete 2.5.6-1, this way people who have already updated can update again.

**Comment by kaikreuzer** [comment]
Yes, just uploading the distro to Bintray (https://ci.openhab.org/view/Release%20Jobs/job/openhab-release/85), should be finishing soon.
If you can deal with the linux package update to 2.5.6-2, it would be great, thanks!

**Comment by kaikreuzer** [comment]
Distro is on Bintray. @BClark09, you can go ahead!

**Comment by BClark09** [comment]
Thanks again Kai, done and available on APT/YUM repos now :)

We can delete 2.5.6-1 at a later time.

**Comment by helmar74** [comment]
Updated to 2.5.6-2, issue is fixed.

Thanks a lot

**Comment by DerOetzi** [comment]
Was the docker image 2.5.6 rebuilt after this fix, because I cannot find this line inside my test instance?

**Comment by wborn** [comment]
Yes it was. That means you're using an up to date image. :-)

**Pull request merged**
