### PR TITLE
Add breaking change alert for ISM8

### PR DESCRIPTION
**Pull request by lsiepel**
add breaking change alert for ISM8

related to: https://github.com/openhab/openhab-addons/pull/14206

### CODE REVIEW

**Review by wborn — CHANGES_REQUESTED** [review]
It should be moved to the right OH version when it gets merged.

**Comment by lsiepel** [comment]
Tried to fix the DCO with commit amend, somehow i failed. Anyway, i guess it should not be an issue as it only is a commit to change the line+ version numbner.

**Review by wborn — CHANGES_REQUESTED** [review]
As there is a 4.1.0 release now, it again should be moved to the right OH version when it gets merged.

**Comment by lsiepel** [comment]
> As there is a 4.1.0 release now, it again should be moved to the right OH version when it gets merged.

Done.

**Review by kaikreuzer — APPROVED** [review]

**Pull request merged**
