### PR TITLE
upgraded to Karaf 4.0.8

### PR DESCRIPTION
**Pull request by kaikreuzer**
implements https://github.com/openhab/openhab-distro/issues/18

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by BClark09** [comment]
image

The branding seems to have lost its way.

**Comment by kaikreuzer** [comment]
Only, if you login via ssh - if it is started on command line, the correct splash screen is shown. Will have to find out where it has the karaf one stored...

@BClark09 There is a critical issue through the update, though: After an apt upgrade, the runtime will fail to start. We need to update a couple of files in userdata/etc.

What would need to be copied from a new package to the users folder is:
```
userdata/etc/*.properties
userdata/etc/org.apache.karaf.*.*
```

When these files are updated by the apt upgrade, it all should work. Could you help doing this change (here on the old packaging)? I unfortunately do not know, where to have a look...

**Comment by kaikreuzer** [comment]
> Only, if you login via ssh - if it is started on command line, the correct splash screen is shown. Will have to find out where it has the karaf one stored...

Ok, this is due to [this change](https://github.com/apache/karaf/pull/210/files) and fixed by https://github.com/openhab/openhab-distro/pull/357

**Comment by BClark09** [comment]
@kaikreuzer I upgraded using apt and was prompted if I wanted to replace the following files to the distributor version:

```
startup.properties
config.properties
distribution.info
org.apache.management.cfg
jre.properties
org.apache.karaf.features.cfg
org.apache.karaf.features.repos.cfg
```

After specifying "yes" to all prompts, I am running a working openHAB (online version).

The default option if the user hits enter on the prompt is to keep the users version, which I suspect is the problem. Do you think that the above files are okay to be overwritten each upgrade? If so then we'll need to extend [these lines](https://github.com/openhab/openhab-distro/blob/master/distributions/pom.xml#L146-L158) so that the files above are set as `<conffile>false</conffile>`

**Comment by ThomDietrich** [comment]
@BClark09 is it possible to define yes as default? That would be the preferable solution, right?

**Comment by kaikreuzer** [comment]
> Do you think that the above files are okay to be overwritten each upgrade? 

Yes, imho all those files can be considered "system" files that the user should not touch. So it is ok to overwrite them.

**Comment by ThomDietrich** [comment]
Okay, then my question is invalid. ;)

**Comment by BClark09** [comment]
#358 should do the trick.

@ThomDietrich it is a very valid question. It would solve many problems like this in the future. I don't know of the answer yet though.

**Comment by kaikreuzer** [comment]
@BClark09 Thanks for helping out. I think we should be able to define which file is a system and which a config file by going through them one by one. But I'd actually like to better separate them as originally intended (system files should really be in "runtime", not "userdata"). I think I'll be able to do some improvements wrt Karaf, but I doubt that I will be able to fully solve it. See also my https://github.com/openhab/openhab-distro/issues/299#issuecomment-268253707.

**Pull request merged**
